# Generated by Django 6.0.7 on 2026-08-03 21:38

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Eindeutiger System-Key (z. B. payment_confirmation)', max_length=50, unique=True, verbose_name='Template Schlüssel')),
                ('name', models.CharField(help_text='Name für die Anzeige im Backend', max_length=100, verbose_name='Name der Vorlage')),
                ('subject', models.CharField(help_text='Unterstützt Platzhalter wie {username}, {event_title} etc.', max_length=200, verbose_name='Betreffzeile')),
                ('content', tinymce.models.HTMLField(help_text='Formatierbarer HTML-Inhalt mit Platzhaltern', verbose_name='E-Mail Inhalt (HTML)')),
                ('is_active', models.BooleanField(default=True, help_text='Deaktivierte Vorlagen werden beim Triggern ignoriert.', verbose_name='Aktiv')),
                ('placeholder_info', models.TextField(blank=True, help_text='Beschreibung der Platzhalter für den Editor', verbose_name='Verfügbare Platzhalter')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zuletzt geändert')),
            ],
            options={
                'verbose_name': 'E-Mail Template',
                'verbose_name_plural': 'E-Mail Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeneralEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(default='noreply@entailsng.de', help_text='Absenderadresse für alle ausgehenden System-E-Mails.', max_length=254, verbose_name='Absender E-Mail-Adresse')),
                ('sender_name', models.CharField(default='EntailsNG Event-Team', help_text='Anzeigename des Absenders (z. B. EntailsNG Team).', max_length=100, verbose_name='Absender Name')),
                ('is_enabled', models.BooleanField(default=True, help_text='Schaltet den automatischen E-Mail-Versand im System ein oder aus.', verbose_name='E-Mail-Versand aktivieren')),
                ('is_sandbox', models.BooleanField(default=False, help_text='Im Sandbox-Modus werden ALLE E-Mails an die unten angegebene Weiterleitungsadresse gesendet.', verbose_name='Sandbox-Modus aktivieren')),
                ('sandbox_redirect_email', models.EmailField(blank=True, default='', help_text='Empfängeradresse im Sandbox-Modus (z. B. orga-test@example.com).', max_length=254, verbose_name='Sandbox Weiterleitungs-Adresse')),
                ('smtp_host', models.CharField(blank=True, default='', help_text='Z. B. smtp.mailgun.org oder smtp.gmail.com. Leer lassen für Django-Standard.', max_length=200, verbose_name='SMTP Host (optional)')),
                ('smtp_port', models.PositiveIntegerField(default=587, verbose_name='SMTP Port')),
                ('smtp_username', models.CharField(blank=True, default='', max_length=150, verbose_name='SMTP Benutzername')),
                ('smtp_password', models.CharField(blank=True, default='', max_length=150, verbose_name='SMTP Passwort')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='TLS Verschlüsselung nutzen')),
            ],
            options={
                'verbose_name': 'Allgemeine E-Mail Einstellung',
                'verbose_name_plural': 'Allgemeine E-Mail Einstellungen',
            },
        ),
    ]
