# Generated by Django 6.0.7 on 2026-08-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalemailsettings',
            name='domain_name',
            field=models.CharField(blank=True, default='', help_text='Eure Haupt-Domain für den DNS-Health Check (z. B. lan-party.de).', max_length=150, verbose_name='E-Mail Versand-Domain'),
        ),
        migrations.AddField(
            model_name='generalemailsettings',
            name='reply_to_email',
            field=models.EmailField(blank=True, default='', help_text='Ziel-Adresse, wenn Gäste auf System-E-Mails antworten (z. B. support@verein.de). Leer lassen = Absender-Adresse.', max_length=254, verbose_name='Antwort E-Mail-Adresse (Reply-To)'),
        ),
    ]
