# Generated by Django 6.0.7 on 2026-08-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_generalemailsettings_domain_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalemailsettings',
            name='smtp_password',
            field=models.CharField(blank=True, default='', help_text='Wird in der Datenbank verschlüsselt gespeichert.', max_length=255, verbose_name='SMTP Passwort'),
        ),
    ]
