# Generated by Django 6.0.7 on 2026-08-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_alter_generalemailsettings_smtp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalemailsettings',
            name='credentials_broken',
            field=models.BooleanField(default=False, help_text='Wird gesetzt, wenn das gespeicherte SMTP-Passwort nicht gelesen werden kann — meist nach Änderung von FIELD_ENCRYPTION_KEY.', verbose_name='Passwort nicht entschlüsselbar'),
        ),
        migrations.AddField(
            model_name='generalemailsettings',
            name='last_send_error',
            field=models.TextField(blank=True, default='', verbose_name='Fehlermeldung'),
        ),
        migrations.AddField(
            model_name='generalemailsettings',
            name='last_send_error_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Letzter Versandfehler'),
        ),
        migrations.AddField(
            model_name='generalemailsettings',
            name='last_test_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Letzter Verbindungstest'),
        ),
        migrations.AddField(
            model_name='generalemailsettings',
            name='last_test_message',
            field=models.TextField(blank=True, default='', verbose_name='Ergebnis des letzten Tests'),
        ),
        migrations.AddField(
            model_name='generalemailsettings',
            name='last_test_ok',
            field=models.BooleanField(blank=True, null=True, verbose_name='Letzter Test erfolgreich'),
        ),
        migrations.AddField(
            model_name='generalemailsettings',
            name='smtp_timeout',
            field=models.PositiveIntegerField(default=10, help_text='Abbruch, wenn der Mailserver nicht antwortet. Empfohlen: 10.', verbose_name='Zeitlimit in Sekunden'),
        ),
        migrations.AddField(
            model_name='generalemailsettings',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False, help_text='Für Port 465. Bei Port 587 stattdessen TLS aktivieren.', verbose_name='SSL statt STARTTLS (Port 465)'),
        ),
        migrations.AddField(
            model_name='generalemailsettings',
            name='transport_mode',
            field=models.CharField(choices=[('unconfigured', 'Noch nicht eingerichtet'), ('env', 'Vom Server vorgegeben (.env)'), ('smtp', 'Eigener SMTP-Server')], default='unconfigured', help_text="Woher die Zugangsdaten für den Mailversand kommen. 'Vom Server vorgegeben' nutzt die Konfiguration aus der .env-Datei.", max_length=20, verbose_name='Versandweg'),
        ),
        migrations.AlterField(
            model_name='generalemailsettings',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Steuert Registrierungsbestätigung, Tickets und Passwort-Reset. Ausgeschaltet können sich keine neuen Gäste registrieren, da die Bestätigungsmail nicht zugestellt wird.', verbose_name='Gäste erhalten E-Mails'),
        ),
        migrations.AlterField(
            model_name='generalemailsettings',
            name='sender_email',
            field=models.EmailField(blank=True, default='', help_text='Adresse, die Gäste als Absender sehen. Muss zu einer bei deinem Mailanbieter verifizierten Domain gehören.', max_length=254, verbose_name='Absenderadresse'),
        ),
        migrations.AlterField(
            model_name='generalemailsettings',
            name='sender_name',
            field=models.CharField(blank=True, default='', help_text="Anzeigename, z. B. 'LAN-Party Orga-Team'.", max_length=100, verbose_name='Absendername'),
        ),
    ]
