# Generated by Django 6.0.7 on 2026-09-19 16:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_set_initial_transport_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(help_text='Zugehöriger E-Mail-Template-Key (z. B. email_verification)', max_length=50, verbose_name='Template Schlüssel')),
                ('recipient_email', models.EmailField(help_text='Zieladresse der Nachricht', max_length=254, verbose_name='Empfängeradresse')),
                ('subject', models.CharField(max_length=255, verbose_name='Betreffzeile')),
                ('body_text', models.TextField(help_text='Reiner Textinhalt der Nachricht', verbose_name='Textinhalt')),
                ('body_html', models.TextField(help_text='HTML-formatierter Inhalt der Nachricht', verbose_name='HTML-Inhalt')),
                ('status', models.CharField(choices=[('PENDING', 'Ausstehend'), ('PROCESSING', 'Wird gesendet'), ('SENT', 'Erfolgreich gesendet'), ('FAILED', 'Fehlgeschlagen')], db_index=True, default='PENDING', max_length=20, verbose_name='Versandstatus')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Bisherige Sendeversuche')),
                ('max_attempts', models.PositiveIntegerField(default=5, verbose_name='Max. Sendeversuche')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Letzte Fehlermeldung')),
                ('scheduled_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Zeitpunkt, ab dem die E-Mail zur Verarbeitung ansteht (für Backoff-Wiederholungen).', verbose_name='Geplanter Versandzeitpunkt')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Erfolgreich gesendet am')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Erstellt am')),
            ],
            options={
                'verbose_name': 'Ausgehende E-Mail',
                'verbose_name_plural': 'Ausgehende E-Mails',
                'ordering': ['scheduled_at', 'created_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='email_queue_status_sched_idx')],
            },
        ),
    ]
