# Generated by Django 6.0.7 on 2026-09-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0006_outgoingemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingemail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Zuletzt geändert'),
        ),
        migrations.AddIndex(
            model_name='outgoingemail',
            index=models.Index(fields=['status', 'updated_at'], name='email_queue_status_upd_idx'),
        ),
    ]
