# Generated by Django 6.0.7 on 2026-09-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0007_outgoingemail_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingemail',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Optionales Ablaufdatum für zeitkritische Nachrichten (z. B. Verifizierungscodes).', null=True, verbose_name='Gültig bis'),
        ),
        migrations.AddField(
            model_name='outgoingemail',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Zeitpunkt, bis zu dem der Worker die exklusive Sperre besitzt.', null=True, verbose_name='Lease läuft ab um'),
        ),
        migrations.AddField(
            model_name='outgoingemail',
            name='worker_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Eindeutige ID des verarbeitenden Worker-Prozesses.', max_length=64, verbose_name='Worker-Kennung'),
        ),
        migrations.AlterField(
            model_name='generalemailsettings',
            name='smtp_password',
            field=models.TextField(blank=True, default='', help_text='Wird in der Datenbank verschlüsselt gespeichert.', verbose_name='SMTP Passwort'),
        ),
        migrations.AlterField(
            model_name='outgoingemail',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ausstehend'), ('PROCESSING', 'Wird gesendet'), ('SENT', 'Erfolgreich gesendet'), ('FAILED', 'Fehlgeschlagen'), ('EXPIRED', 'Abgelaufen')], db_index=True, default='PENDING', max_length=20, verbose_name='Versandstatus'),
        ),
        migrations.AddIndex(
            model_name='outgoingemail',
            index=models.Index(fields=['status', 'lease_expires_at'], name='email_queue_status_lease_idx'),
        ),
    ]
