# Generated by Django 6.0.7 on 2026-10-08 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0008_outgoingemail_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingemail',
            name='contact_ip_hash',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=64, verbose_name='Kontakt-IP-Kennung'),
        ),
        migrations.AddField(
            model_name='outgoingemail',
            name='contact_submission_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, verbose_name='Kontaktanfrage-ID'),
        ),
        migrations.AddField(
            model_name='outgoingemail',
            name='reply_to_email',
            field=models.EmailField(blank=True, db_index=True, default='', help_text='Individuelles Reply-To; leer verwendet die allgemeine E-Mail-Konfiguration.', max_length=254, verbose_name='Antwortadresse'),
        ),
        migrations.AddField(
            model_name='outgoingemail',
            name='submitted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_emails', to=settings.AUTH_USER_MODEL, verbose_name='Anfragender Benutzer'),
        ),
        migrations.AddConstraint(
            model_name='outgoingemail',
            constraint=models.UniqueConstraint(fields=('contact_submission_id', 'recipient_email'), name='unique_contact_email_recipient'),
        ),
    ]
