TEXTS = {
    'backup_title': 'Backups',
    'backup_create': 'Backup erstellen',
    'backup_upload': 'Backup hochladen und prüfen',
    'backup_download': 'Herunterladen',
    'backup_restore': 'Wiederherstellung vorbereiten',
    'backup_confirm_restore': 'Datenbestand jetzt wiederherstellen',
    'backup_delete': 'Backup löschen',
    'backup_delete_confirm': 'Dieses Backup endgültig löschen?',
    'backup_description': 'Beschreibung',
    'backup_password': 'Aktuelles Administratorpasswort',
    'backup_file': 'Backup-Datei',
    'backup_created': 'Erstellt',
    'backup_size': 'Größe',
    'backup_database': 'Datenbank',
    'backup_software': 'Softwarestand (Prüfsumme)',
    'backup_file_count': 'Enthaltene Dateien',
    'backup_unpacked_size': 'Entpackter Datenumfang',
    'backup_scope': 'Datenbank, öffentliche Medien und private Medien',
    'backup_scope_label': 'Umfang',
    'backup_check': 'Sicherung prüfen',
    'backup_status': 'Status',
    'backup_empty': 'Noch keine Backups vorhanden.',
    'backup_back': 'Zur Backup-Übersicht',
    'backup_home': 'Administration',
    'backup_notice': 'Sichert die Datenbank sowie öffentliche und private Medien. Während der Aufnahme des Datenbestands ist die Anwendung vorübergehend im Wartungsmodus.',
    'backup_keys_notice': 'Backups sind verschlüsselt. Bewahre den Backup-Schlüssel und die Schlüssel für gespeicherte Zugangsdaten zusätzlich außerhalb dieses Servers auf.',
    'backup_restore_notice': 'Alle aktuellen Anwendungsdaten und Medien werden durch den Sicherungsstand ersetzt. Eine Sicherung des aktuellen Zustands wird automatisch erstellt. Anschließend musst du dich mit einem Administratorkonto aus dem Backup anmelden. Der E-Mail-Versand bleibt bis zur manuellen Freigabe pausiert.',
    'backup_confirm': 'Ich bestätige, dass der aktuelle Datenbestand vollständig ersetzt wird.',
    'backup_maintenance_confirm': 'Ich bestätige das vorübergehende Wartungsfenster.',
    'backup_pending': 'Wartet auf Verarbeitung',
    'backup_running': 'Wird verarbeitet',
    'backup_completed': 'Abgeschlossen',
    'backup_failed': 'Fehlgeschlagen',
    'backup_interrupted': 'Unterbrochen – Wiederaufnahme erforderlich',
    'backup_recovery_required': 'Rücksetzung erforderlich',
    'backup_prepared': 'Geprüft – bereit zur Wiederherstellung',
    'backup_uploaded': 'Hochgeladen – noch ungeprüft',
    'backup_queued': 'Der Auftrag wurde zur Verarbeitung vorgemerkt.',
    'backup_deleted': 'Das Backup wurde gelöscht.',
    'backup_job_title': 'Backup-Auftrag',
    'backup_job_hint': 'Diese Seite aktualisiert sich während der Verarbeitung. Du kannst das Fenster schließen; der Auftrag läuft unabhängig weiter.',
    'backup_worker_missing': 'Der Backup-Worker ist nicht erreichbar. Starte process_backup_jobs, bevor du einen Auftrag anlegst.',
    'backup_stage_validate': 'Sicherung prüfen',
    'backup_stage_snapshot': 'Datenbestand sichern',
    'backup_stage_package': 'Backup verpacken und verschlüsseln',
    'backup_stage_prepare': 'Wiederherstellung prüfen',
    'backup_stage_safety': 'Aktuellen Zustand sichern',
    'backup_stage_apply': 'Datenbank und Medien übernehmen',
    'backup_stage_verify': 'Wiederhergestellten Zustand prüfen',
    'backup_stage_rollback': 'Vorherigen Zustand zurücksetzen',
    'backup_maintenance': 'Entails-NG wird gewartet. Bitte versuche es nach Abschluss erneut.',
    'backup_mail_paused': 'Der E-Mail-Versand ist nach einer Wiederherstellung pausiert. Prüfe die Versandwarteschlange und gib ihn anschließend hier frei.',
    'backup_resume_mail': 'Geprüfte E-Mail-Warteschlange freigeben',
    'backup_mail_resumed': 'Die zusätzliche Versandsperre wurde aufgehoben. Die normalen E-Mail-Einstellungen gelten weiterhin.',
    'backup_err_key': 'BACKUP_ENCRYPTION_KEY fehlt oder ist ungültig. Benötigt wird ein Base64-URL-kodierter Schlüssel mit 32 zufälligen Bytes.',
    'backup_err_paths': 'Backup-, Medien- und Static-Verzeichnisse müssen getrennt sein und dürfen keine unsicheren Dateiverweise enthalten.',
    'backup_err_space': 'Nicht genügend freier Speicherplatz für diesen Vorgang.',
    'backup_err_busy': 'Eine Sicherung oder Wiederherstellung läuft bereits.',
    'backup_err_maintenance': 'Der Wartungsmodus ist aktiv. Eine unterbrochene Wiederherstellung muss zuerst fortgesetzt oder zurückgesetzt werden.',
    'backup_err_archive': 'Die Datei ist beschädigt, stammt nicht aus einer vertrauenswürdigen Sicherung oder wurde mit einem anderen Backup-Schlüssel erstellt.',
    'backup_err_limits': 'Die Sicherung überschreitet die konfigurierten Größen- oder Dateianzahlgrenzen.',
    'backup_err_compatible': 'Die Sicherung passt nicht zu Datenbanktyp, Softwarestand oder Migrationsstand dieser Installation.',
    'backup_err_credentials': 'Die verschlüsselten Zugangsdaten aus dem Backup sind mit dem vorhandenen Schlüssel nicht lesbar.',
    'backup_err_database': 'Die Datenbanksicherung konnte nicht erstellt, geprüft oder wiederhergestellt werden. Details stehen im Serverprotokoll.',
    'backup_err_tools': 'Passende PostgreSQL-Programme pg_dump und pg_restore fehlen oder die Datenbankrolle hat keine Berechtigung zum Anlegen einer Prüfdatenbank.',
    'backup_err_references': 'Die Sicherung enthält fehlende Dateireferenzen oder keinen aktiven Administratorzugang.',
    'backup_err_not_found': 'Das angeforderte Backup oder der Auftrag ist nicht verfügbar.',
    'backup_err_password': 'Das Administratorpasswort ist nicht korrekt.',
    'backup_err_timeout': 'Laufende Zugriffe konnten nicht rechtzeitig abgeschlossen werden. Der Vorgang wurde abgebrochen.',
    'backup_err_operation': 'Der Vorgang konnte nicht abgeschlossen werden. Details stehen im Serverprotokoll.',
}
