# Generated by Django 6.0.7 on 2026-07-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onboarding_ticket_enabled', models.BooleanField(default=True, help_text='Globale Hauptschalter: Soll das Onboardingticket generell angezeigt werden?', verbose_name='Onboardingticket anzeigen')),
                ('onboarding_ticket_event_dependent', models.BooleanField(default=True, help_text='Wenn aktiv, wird das Ticket nur angezeigt, wenn ein aktives Event in der Zukunft liegt.', verbose_name='Onboardingticket anzeigen Event abhängig')),
                ('onboarding_ticket_dynamic_display', models.BooleanField(default=False, help_text='False = Immer anzeigen (sofern Event-Bedingung erfüllt), True = Nur innerhalb des definierten Zeitraums vor dem Event anzeigen.', verbose_name='Dynamische Anzeige')),
                ('onboarding_ticket_days_before_event', models.PositiveIntegerField(default=14, help_text='Anzahl der Tage vor dem Event-Start. Nur in diesem Zeitraum wird das Ticket angezeigt (sofern Dynamische Anzeige aktiv ist).', verbose_name='Zeit bis zum Event (Tage)')),
            ],
            options={
                'verbose_name': 'Feature-Konfiguration',
                'verbose_name_plural': 'Feature-Konfigurationen',
            },
        ),
        migrations.CreateModel(
            name='TranslationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Interner Bezeichner, z. B. 'onboarding_ticket_title'", max_length=100, unique=True, verbose_name='Schlüssel (Key)')),
                ('value', models.TextField(help_text='Der im Frontend oder Backend angezeigte Text.', verbose_name='Text / Wording')),
                ('description', models.CharField(blank=True, help_text='Kurze Erläuterung, wo dieser Text verwendet wird.', max_length=255, verbose_name='Beschreibung / Verwendungsort')),
            ],
            options={
                'verbose_name': 'Wording / Übersetzung',
                'verbose_name_plural': 'Wordings / Übersetzungen',
                'ordering': ['key'],
            },
        ),
    ]
