# Generated by Django 6.0.7 on 2026-07-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Anzeigename im Menü (z. B. Übersicht, Sitzplan)', max_length=100)),
                ('url_name', models.CharField(help_text='Django URL-Name (z. B. dashboard, seating_plan)', max_length=100)),
                ('icon_svg', models.TextField(blank=True, help_text='SVG-Code für das Icon (20x20px empfohlen)')),
                ('badge_text', models.CharField(blank=True, help_text='Optionales Badge (z. B. "2" oder "NEU")', max_length=10, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Sortierung (kleinere Zahlen stehen weiter oben bzw. links)')),
                ('is_active', models.BooleanField(default=True, help_text='Im Menü anzeigen?')),
            ],
            options={
                'verbose_name': 'Menüpunkt',
                'verbose_name_plural': 'Menüpunkte',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SystemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Eindeutiger Übersetzungsschlüssel (z. B. seat_card_title)', max_length=255, unique=True)),
                ('text', models.TextField(blank=True, default='', help_text='Der im Frontend angezeigte Text für diesen Schlüssel')),
            ],
            options={
                'verbose_name': 'Übersetzung',
                'verbose_name_plural': 'Übersetzungen',
                'ordering': ['key'],
            },
        ),
        migrations.DeleteModel(
            name='FeatureConfig',
        ),
        migrations.DeleteModel(
            name='TranslationConfig',
        ),
    ]
