# Generated by Django 6.0.7 on 2026-07-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_navigationitem_systemtranslation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationitem',
            name='badge_text',
            field=models.CharField(blank=True, default='', help_text='Optionales Badge, z. B. "2" oder "NEU"', max_length=10),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Kleinere Zahlen stehen weiter oben bzw. links'),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='url_name',
            field=models.CharField(help_text='Django URL-Name, z. B. dashboard, news_list, seating_plan', max_length=100),
        ),
    ]
