# Generated by Django 6.0.7 on 2026-07-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_alter_navigationitem_badge_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Lesbarer Name der Funktion (z. B. Onboarding Ticket)', max_length=100, verbose_name='Feature Name')),
                ('key', models.CharField(help_text='Eindeutiger Bezeichner (z. B. onboarding_ticket, seating_module)', max_length=100, unique=True, verbose_name='Schlüssel (Key)')),
                ('is_enabled', models.BooleanField(default=True, help_text='Schaltet dieses Feature im System ein oder aus', verbose_name='Aktiviert')),
                ('description', models.TextField(blank=True, help_text='Erläuterung zur Funktion dieses Feature Flags', verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'ordering': ['name'],
            },
        ),
    ]
