# Generated by Django 6.0.7 on 2026-08-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_featureflag'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_enabled', models.BooleanField(default=True, help_text='Schaltet die Anzeige des Ticket-Bereichs auf dem Dashboard generell ein oder aus.', verbose_name='Ticket anzeigen')),
                ('ticket_days_before_event', models.PositiveIntegerField(default=0, help_text='Anzahl der Tage vor dem Event. Bei > 0 wird das Ticket erst in diesem Zeitraum vor Event-Start angezeigt (0 = immer anzeigen).', verbose_name='Ticket nur anzeigen X Tage vor Event-Start')),
                ('ticket_requires_payment', models.BooleanField(default=False, help_text='Wenn aktiviert, sieht der Gast die Ticket-Karte auf dem Dashboard erst, nachdem seine Zahlung verbucht wurde.', verbose_name='Ticket nur anzeigen, wenn der Gast eingezahlt hat')),
            ],
            options={
                'verbose_name': 'Allgemeine Konfiguration',
                'verbose_name_plural': 'Allgemeine Konfiguration',
            },
        ),
    ]
