# Generated by Django 6.0.7 on 2026-08-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_generalconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Entails', help_text='Name des Events / der Plattform (z. B. Entails, FragFest)', max_length=100, verbose_name='Systemname')),
                ('brand_accent_text', models.CharField(blank=True, default='NG', help_text='Hervorgehobenes Wort im Logo/Header (z. B. NG, 2026)', max_length=50, verbose_name='Akzent-Suffix')),
                ('site_tagline', models.CharField(blank=True, default='Event Control', help_text='Kurzer Untertitel unter dem Markennamen (z. B. Event Control, LAN-Party CMS)', max_length=100, verbose_name='Untertitel')),
                ('logo', models.ImageField(blank=True, help_text='Optionales Logo-Bild. Wenn leer, wird das Standard-Icon / Text-Logo verwendet.', null=True, upload_to='branding/', verbose_name='Custom Logo-Bild')),
                ('theme_preset', models.CharField(choices=[('WARM_AMBER', 'Warm Amber (Default)'), ('CYBERPUNK', 'Cyberpunk Neon'), ('SLATE_BLUE', 'Slate Blue'), ('EMERALD', 'Emerald Gaming'), ('CUSTOM', 'Benutzerdefiniert')], default='WARM_AMBER', help_text='Wähle ein vorgefertigtes Farbschema.', max_length=30, verbose_name='Design-Theme (Preset)')),
                ('primary_color', models.CharField(blank=True, help_text='Hex-Code (z. B. #f8ab2d). Überschreibt die Akzentfarbe des Presets.', max_length=20, verbose_name='Benutzerdefinierte Akzentfarbe (--signal)')),
                ('secondary_color', models.CharField(blank=True, help_text='Hex-Code (z. B. #332719). Überschreibt die Hauptfarbe der Sidebar/Header.', max_length=20, verbose_name='Benutzerdefinierte Hauptfarbe (--navy)')),
                ('background_color', models.CharField(blank=True, help_text='Hex-Code (z. B. #fffaf2). Überschreibt die Hintergrundfarbe.', max_length=20, verbose_name='Benutzerdefinierte Hintergrundfarbe (--paper)')),
                ('impressum_content', models.TextField(blank=True, default='<h3>Impressum</h3><p>EntailsNG LAN-Party CMS</p>', help_text='Inhalt für die Impressum-Seite / Modal. Unterstützt HTML.', verbose_name='Impressum')),
                ('datenschutz_content', models.TextField(blank=True, default='<h3>Datenschutzerklärung</h3><p>Informationen zum Datenschutz...</p>', help_text='Inhalt für die Datenschutz-Seite / Modal. Unterstützt HTML.', verbose_name='Datenschutzerklärung')),
                ('custom_css', models.TextField(blank=True, help_text='Wird direkt im <head> aller Seiten eingebunden.', verbose_name='Benutzerdefiniertes CSS')),
            ],
            options={
                'verbose_name': 'Individualisierung & Branding',
                'verbose_name_plural': 'Individualisierung & Branding',
            },
        ),
    ]
