# Generated by Django 6.0.7 on 2026-08-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_sitecustomization'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecustomization',
            name='nav_scale',
            field=models.CharField(choices=[('XS', 'Sehr klein'), ('SM', 'Klein'), ('MD', 'Mittel (Standard)'), ('LG', 'Groß'), ('XL', 'Sehr groß')], default='MD', help_text='Steuert die Skalierung und Schriftgröße der seitlichen sowie mobilen Navigation.', max_length=10, verbose_name='Navigations-Darstellungsgröße'),
        ),
    ]
