# Generated by Django 6.0.7 on 2026-08-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_sitecustomization_nav_scale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitecustomization',
            name='nav_scale',
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='ui_scale',
            field=models.CharField(choices=[('XS', 'Sehr klein'), ('SM', 'Klein'), ('MD', 'Mittel (Standard)'), ('LG', 'Groß'), ('XL', 'Sehr groß')], default='MD', help_text='Steuert die Gesamt-Skalierung und Schriftgrößen des gesamten Frontends (Navigation, Karten, Buttons, Formulare, Überschriften).', max_length=10, verbose_name='System-Darstellungsgröße (UI-Skalierung)'),
        ),
    ]
