# Generated by Django 6.0.7 on 2026-08-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_remove_sitecustomization_nav_scale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalconfiguration',
            name='expired_ticket_mode',
            field=models.CharField(choices=[('WORN', 'Ticket abgenutzt (Mit "Veranstaltung beendet" Hinweis anzeigen)'), ('HIDE', 'Event beendet (Automatisch ausblenden bei Event-Ende)')], default='WORN', help_text='Bestimmt das Verhalten der Ticket-Karte auf dem Dashboard, wenn das Event-Enddatum überschritten ist.', max_length=10, verbose_name='Verhalten bei abgelaufenen Veranstaltungen'),
        ),
    ]
