# Generated by Django 6.0.7 on 2026-08-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0009_generalconfiguration_expired_ticket_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalconfiguration',
            name='debug_mode',
            field=models.BooleanField(default=False, help_text='Aktiviert die detaillierte technische Django-Fehlerseite bei Serverfehlern. Im normalen Live-Betrieb sollte dies deaktiviert sein.', verbose_name='Debug-Modus (Detaillierte Fehlerausgabe)'),
        ),
    ]
