# Generated by Django 6.0.7 on 2026-08-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0011_navigationitem_icon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationitem',
            name='icon_name',
            field=models.CharField(choices=[('dashboard', 'Dashboard / Übersicht (Home)'), ('tournaments', 'Turniere (Pokal / Trophy)'), ('teams', 'Teams (Spielergruppe)'), ('seating', 'Sitzplan (Raster / Grid)'), ('info', 'Informationen (Info-Kreis)'), ('news', 'Neuigkeiten (Zeitung / Feed)'), ('clans', 'Clans (Schild / Wappen)'), ('rules', 'Regeln & FAQ (Buch / Dokument)'), ('support', 'Support & Hilfe (Rettungsring)'), ('shop', 'Shop & Catering (Einkaufswagen)'), ('settings', 'Einstellungen (Regler)'), ('sponsors', 'Sponsoren (Stern / Partner)'), ('custom', 'Benutzerdefiniertes SVG (Nur Superuser)')], default='dashboard', help_text='Wähle ein sicheres Standard-Icon aus der Liste.', max_length=50, verbose_name='Icon-Auswahl'),
        ),
    ]
