# Generated by Django 6.0.7 on 2026-08-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0012_alter_navigationitem_icon_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeatureFlag',
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='url_name',
            field=models.CharField(help_text='Django URL-Name oder Modulkürzel, z. B. dashboard, teams, tournaments, seating, news, info, clans, sponsors', max_length=100),
        ),
    ]
