# Generated by Django 6.0.7 on 2026-08-30 20:22

import configuration.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0013_delete_featureflag_alter_navigationitem_url_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalconfiguration',
            name='bic',
            field=models.CharField(blank=True, help_text='Optional: BIC der Empfängerbank (8 oder 11 Zeichen).', max_length=11, validators=[configuration.validators.validate_bic], verbose_name='BIC / SWIFT'),
        ),
        migrations.AddField(
            model_name='generalconfiguration',
            name='iban',
            field=models.CharField(blank=True, help_text='IBAN des Empfängerkontos für SEPA-Überweisungen (ohne Leerzeichen gespeichert).', max_length=34, validators=[configuration.validators.validate_iban], verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='generalconfiguration',
            name='kontoinhaber',
            field=models.CharField(blank=True, help_text='Name des Empfängers / Kontoinhabers (max. 70 Zeichen für EPC-QR-Standard).', max_length=70, verbose_name='Kontoinhaber'),
        ),
    ]
