# Generated by Django 6.0.7 on 2026-09-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0014_generalconfiguration_bic_generalconfiguration_iban_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecustomization',
            name='theme_preset',
            field=models.CharField(choices=[('WARM_AMBER', 'Warm Amber (Default)'), ('CYBERPUNK', 'Cyberpunk Neon'), ('SLATE_BLUE', 'Slate Blue'), ('EMERALD', 'Emerald Gaming'), ('QUAKE_99', 'Quake 99 (Retro LAN)'), ('ARENA_PRO', 'Arena Pro (Esports Tactical)'), ('CYBERDECK', 'Cyberdeck (Neon Synthwave)'), ('MAINFRAME', 'Mainframe (Terminal Green)'), ('DAYLIGHT', 'Daylight Projector (High-Contrast Light)'), ('CUSTOM', 'Benutzerdefiniert')], default='WARM_AMBER', help_text='Wähle ein vorgefertigtes Farbschema.', max_length=30, verbose_name='Design-Theme (Preset)'),
        ),
    ]
