# Generated by Django 6.0.7 on 2026-09-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0015_alter_sitecustomization_theme_preset'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Zeitpunkt')),
                ('path', models.CharField(max_length=500, verbose_name='URL / Pfad')),
                ('method', models.CharField(default='GET', max_length=10, verbose_name='HTTP-Methode')),
                ('exception_type', models.CharField(db_index=True, max_length=255, verbose_name='Ausnahme-Typ')),
                ('error_message', models.TextField(verbose_name='Fehlermeldung')),
                ('traceback', models.TextField(verbose_name='Python-Traceback')),
                ('user', models.CharField(blank=True, default='Anonym', max_length=150, verbose_name='Benutzer')),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True, verbose_name='IP-Adresse')),
                ('resolved', models.BooleanField(db_index=True, default=False, verbose_name='Behoben?')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Behoben am')),
            ],
            options={
                'verbose_name': 'System-Fehlerprotokoll',
                'verbose_name_plural': 'System-Fehlerprotokolle',
                'ordering': ['-timestamp'],
            },
        ),
    ]
