# Generated by Django 6.0.7 on 2026-09-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0016_systemerrorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalconfiguration',
            name='ticket_requires_login',
            field=models.BooleanField(default=False, help_text='Wenn aktiviert, sieht der Gast die Ticket-Karte auf dem Dashboard erst, nachdem er sich angemeldet hat (für nicht eingeloggte Besucher wird sie verborgen).', verbose_name='Ticket nur anzeigen, wenn der Gast eingeloggt ist'),
        ),
    ]
