# Generated by Django 6.0.7 on 2026-09-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0017_generalconfiguration_ticket_requires_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationitem',
            name='title',
            field=models.CharField(help_text='Anzeigename im Menü (z. B. Übersicht, Sitzplan)', max_length=200),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='url_name',
            field=models.CharField(help_text='Django URL-Name oder Modulkürzel, z. B. dashboard, teams, tournaments, seating, news, info, clans, sponsors', max_length=255),
        ),
    ]
