# Generated by Django 6.0.7 on 2026-10-04 10:49

from django.db import migrations, models


def seed_config(apps, schema_editor):
    apps.get_model('configuration', 'ClanSeatConfiguration').objects.get_or_create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0020_navigationitem_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanSeatConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Deaktivieren gibt alle offenen Clan-Vormerkungen frei. Persönliche Buchungen bleiben erhalten.', verbose_name='Aktiv')),
                ('default_limit', models.PositiveIntegerField(default=8, help_text='Kontingent pro Clan und Veranstaltung. Bereits übernommene Plätze zählen mit.', verbose_name='Anzahl vormerkbarer Sitzplätze')),
                ('duration', models.CharField(choices=[('EVENT', 'Veranstaltungszeitraum'), ('DAYS', 'Zeitraum ab erster Vormerkung des Clans'), ('FIXED', 'Fixer Zeitpunkt')], default='EVENT', max_length=5, verbose_name='Dauer der Vormerkung')),
                ('days', models.PositiveIntegerField(default=14, help_text='Nur beim Tagesmodus; jeder Clan startet mit seiner ersten bestätigten Vormerkung.', verbose_name='Dauer in Tagen')),
                ('deadline', models.DateTimeField(blank=True, help_text='Nur beim fixen Zeitpunkt. Zeitzone: Europe/Vienna.', null=True, verbose_name='Gültig bis')),
            ],
            options={
                'verbose_name': 'Clan Sitzplatz Vormerkung',
                'verbose_name_plural': 'Clan Sitzplatz Vormerkung',
                'constraints': [models.CheckConstraint(condition=models.Q(('pk', 1)), name='clan_seat_config_singleton')],
            },
        ),
        migrations.RunPython(seed_config, migrations.RunPython.noop),
    ]
