# Generated by Django 6.0.7 on 2026-10-05 10:54

import configuration.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0021_clan_seat_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecustomization',
            name='background_color',
            field=models.CharField(blank=True, help_text='Hex-Code (z. B. #fffaf2). Überschreibt die Hintergrundfarbe.', max_length=20, validators=[configuration.validators.validate_hex_color], verbose_name='Benutzerdefinierte Hintergrundfarbe (--paper)'),
        ),
        migrations.AlterField(
            model_name='sitecustomization',
            name='primary_color',
            field=models.CharField(blank=True, help_text='Hex-Code (z. B. #f8ab2d). Überschreibt die Akzentfarbe des Presets.', max_length=20, validators=[configuration.validators.validate_hex_color], verbose_name='Benutzerdefinierte Akzentfarbe (--signal)'),
        ),
        migrations.AlterField(
            model_name='sitecustomization',
            name='secondary_color',
            field=models.CharField(blank=True, help_text='Hex-Code (z. B. #332719). Überschreibt die Hauptfarbe der Sidebar/Header.', max_length=20, validators=[configuration.validators.validate_hex_color], verbose_name='Benutzerdefinierte Hauptfarbe (--navy)'),
        ),
    ]
