# Generated by Django 6.0.7 on 2026-10-07 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0022_sitecustomization_color_validators'),
        ('events', '0014_eventregistration_booking_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanseatconfiguration', name='enabled',
            field=models.BooleanField(default=False, help_text='Deaktivieren gibt offene Vormerkungen ohne Sammelauftrag frei. Sammelaufträge und persönliche Buchungen bleiben erhalten.', verbose_name='Aktiv'),
        ),
        migrations.AddField(
            model_name='clanseatconfiguration',
            name='payment_days',
            field=models.PositiveIntegerField(default=7, verbose_name='Zahlungsfrist in Kalendertagen'),
        ),
        migrations.AddField(
            model_name='clanseatconfiguration',
            name='payment_review_days',
            field=models.PositiveIntegerField(default=2, help_text='Zusätzliche Zeit für die Orga. Beide Fristen enden spätestens mit der ursprünglichen Vormerkfrist.', verbose_name='Prüfzeit in Kalendertagen'),
        ),
        migrations.AddField(
            model_name='clanseatconfiguration',
            name='payment_ticket_type',
            field=models.ForeignKey(blank=True, help_text='Bei genau einer aktiven Kategorie wird diese automatisch verwendet. Sonst hier eine Kategorie der aktiven Veranstaltung festlegen.', null=True, on_delete=django.db.models.deletion.PROTECT, to='events.tickettype', verbose_name='Ticketkategorie für Clan-Sammelzahlungen'),
        ),
        migrations.AddConstraint(
            model_name='clanseatconfiguration',
            constraint=models.CheckConstraint(condition=models.Q(('payment_days__gte', 1)), name='clan_payment_days_positive'),
        ),
    ]
