# Generated by Django 6.0.7 on 2026-10-08 15:15

import configuration.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0023_clanseatconfiguration_payment_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalconfiguration',
            name='contact_enabled',
            field=models.BooleanField(default=False, help_text='Erlaubt Kontaktanfragen auch ohne Anmeldung. Benötigt aktive Betreffkategorien und einen eingerichteten E-Mail-Versand.', verbose_name='Kontaktformular aktivieren'),
        ),
        migrations.AddField(
            model_name='generalconfiguration',
            name='contact_recipient_emails',
            field=models.TextField(blank=True, default='', help_text='Eine oder mehrere E-Mail-Adressen, getrennt mit ; (maximal 20). Kategorien ohne eigene Empfänger verwenden diese Liste.', max_length=6000, validators=[configuration.validators.validate_contact_recipients], verbose_name='Standardempfänger für Kontaktanfragen'),
        ),
        migrations.CreateModel(
            name='ContactCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Betreffkategorie')),
                ('recipient_emails', models.TextField(blank=True, default='', help_text='Mit ; trennen (maximal 20). Leer lassen, um die Standardempfänger zu verwenden.', max_length=6000, validators=[configuration.validators.validate_contact_recipients], verbose_name='Empfängeradressen')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_categories', to='configuration.generalconfiguration')),
            ],
            options={
                'verbose_name': 'Kontakt-Betreffkategorie',
                'verbose_name_plural': 'Kontakt-Betreffkategorien',
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('configuration'), name='unique_contact_category_name')],
            },
        ),
    ]
