# Generated by Django 6.0.7 on 2026-08-04 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='6-stelliger Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Ablaufdatum')),
                ('is_used', models.BooleanField(default=False, verbose_name='Verwendet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'E-Mail Verifizierungscode',
                'verbose_name_plural': 'E-Mail Verifizierungscodes',
                'ordering': ['-created_at'],
            },
        ),
    ]
