# Generated by Django 6.0.7 on 2026-08-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_failed_login_attempts_user_locked_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Fehlgeschlagene Versuche'),
        ),
    ]
