# Generated by Django 6.0.7 on 2026-09-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='new_email',
            field=models.EmailField(blank=True, help_text='Wird bei E-Mail-Änderungen im Profil gesetzt. Bleibt bei Erstregistrierung leer.', max_length=254, null=True, verbose_name='Neue E-Mail-Adresse'),
        ),
    ]
