# Generated by Django 6.0.7 on 2026-10-07 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_existing_active_accounts(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(is_active=True, deleted_at__isnull=True).update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, editable=False, verbose_name='E-Mail bestätigt'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False, editable=False, verbose_name='Durch Orga gesperrt'),
        ),
        migrations.AddField(
            model_name='user',
            name='session_version',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.RunPython(mark_existing_active_accounts, migrations.RunPython.noop),
        migrations.CreateModel(
            name='UserBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=1000, verbose_name='Interne Begründung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('was_active', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.TextField(blank=True, max_length=1000)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orga_bans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orga-Sperre',
                'verbose_name_plural': 'Orga-Sperren',
                'ordering': ('-created_at', '-pk'),
                'permissions': [('manage_user_bans', 'Benutzer global sperren und Sperren aufheben')],
            },
        ),
        migrations.CreateModel(
            name='BannedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=64)),
                ('key_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_identities', to='users.userban')),
            ],
        ),
        migrations.CreateModel(
            name='UserBanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BAN', 'Sperren'), ('UNBAN', 'Aufheben'), ('ADD_EMAIL', 'Adresse ergänzen')], max_length=12)),
                ('reason', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ban', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='users.userban')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='userban',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True), ('user__isnull', False)), fields=('user',), name='one_active_orga_ban_per_user'),
        ),
        migrations.AddConstraint(
            model_name='bannedemail',
            constraint=models.UniqueConstraint(fields=('ban', 'fingerprint'), name='unique_email_identity_per_ban'),
        ),
    ]
