# Generated by Django 6.0.7 on 2026-07-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titel')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-Slug')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Veranstaltungsort')),
                ('start_date', models.DateTimeField(verbose_name='Startzeitpunkt')),
                ('end_date', models.DateTimeField(verbose_name='Endzeitpunkt')),
                ('max_guests', models.PositiveIntegerField(default=50, verbose_name='Max. Teilnehmer')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Ticketpreis (€)')),
                ('status', models.CharField(choices=[('DRAFT', 'Entwurf'), ('OPEN', 'Anmeldung geöffnet'), ('RUNNING', 'Läuft aktuell'), ('FINISHED', 'Beendet'), ('CANCELLED', 'Absagt')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zuletzt geändert')),
            ],
            options={
                'verbose_name': 'Veranstaltung',
                'verbose_name_plural': 'Veranstaltungen',
                'ordering': ['-start_date'],
            },
        ),
    ]
