# Generated by Django 6.0.7 on 2026-07-21 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Entwurf'), ('OPEN', 'Anmeldung geöffnet'), ('RUNNING', 'Läuft aktuell'), ('FINISHED', 'Beendet'), ('CANCELLED', 'Abgesagt')], default='DRAFT', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kategorie Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preis (€)')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Hinweis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.event', verbose_name='Veranstaltung')),
            ],
            options={
                'verbose_name': 'Ticket-Kategorie',
                'verbose_name_plural': 'Ticket-Kategorien',
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Offen'), ('PAID', 'Bezahlt'), ('CANCELLED', 'Storniert')], default='UNPAID', max_length=20, verbose_name='Bezahlstatus')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Tatsächlich bezahlter Betrag (€)')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Bezahlt am')),
                ('is_checked_in', models.BooleanField(default=False, verbose_name='Eingecheckt (Vor Ort)')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Check-in Zeitpunkt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angemeldet am')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event', verbose_name='Veranstaltung')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
                ('ticket_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.tickettype', verbose_name='Gewähltes Ticket')),
            ],
            options={
                'verbose_name': 'Anmeldung',
                'verbose_name_plural': 'Anmeldungen',
                'unique_together': {('user', 'event')},
            },
        ),
    ]
