# Generated by Django 6.0.7 on 2026-07-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_status_tickettype_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Nur EINE Veranstaltung sollte gleichzeitig aktiv sein!', verbose_name='Aktive Hauptveranstaltung'),
        ),
    ]
