# Generated by Django 6.0.7 on 2026-07-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='is_checked_in',
            field=models.BooleanField(default=False, help_text='Gibt an, ob der Gast vor Ort eingecheckt hat.', verbose_name='Eingecheckt (Vor Ort)'),
        ),
    ]
