# Generated by Django 6.0.7 on 2026-07-24 19:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_eventregistration_is_checked_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='checkin_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Eindeutiges Token für den QR-Code Einlass-Scan', verbose_name='Check-in Secret Token'),
        ),
    ]
