# Generated by Django 6.0.7 on 2026-08-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_eventregistration_checkin_token'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='only_one_active_event', violation_error_message='Es kann immer nur genau eine Hauptveranstaltung gleichzeitig aktiv sein.'),
        ),
    ]
