# Generated by Django 6.0.7 on 2026-08-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_only_one_active_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Storniert am'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Wird bei Bezahlung automatisch mit dem Ticketpreis initialisiert, falls nicht manuell angegeben.', max_digits=6, verbose_name='Tatsächlich bezahlter Betrag (€)'),
        ),
    ]
