# Generated by Django 6.0.7 on 2026-08-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventregistration_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='event_end_date_after_start_date', violation_error_message='Das Enddatum muss nach dem Startdatum liegen.'),
        ),
    ]
