# Generated by Django 6.0.7 on 2026-09-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_eventregistration_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_unpaid_seat_overwrite',
            field=models.BooleanField(choices=[(True, 'Ja, Überschreibung nicht bezahlter Gäste möglich'), (False, 'Nein, Überschreibung nicht bezahlter Gäste möglich')], default=True, help_text='Legt fest, ob zahlende Gäste vorgemerkte Plätze unbezahlter Teilnehmer übernehmen dürfen.', verbose_name='Sitzplatz-Überschreibung nicht bezahlter Gäste'),
        ),
    ]
