# Generated by Django 6.0.7 on 2026-09-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_allow_unpaid_seat_overwrite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_date'], 'permissions': [('can_update_payment_check', 'Kann Zeitpunkt des letzten Kontochecks aktualisieren')], 'verbose_name': 'Veranstaltung', 'verbose_name_plural': 'Veranstaltungen'},
        ),
        migrations.AddField(
            model_name='event',
            name='last_payment_check',
            field=models.DateTimeField(blank=True, help_text='Zeitpunkt, an dem die Banküberweisungen zuletzt mit den Anmeldungen abgeglichen wurden.', null=True, verbose_name='Letzter Kontocheck'),
        ),
    ]
