# Generated by Django 6.0.7 on 2026-09-22 14:39

from django.db import migrations, models


def populate_booking_price(apps, schema_editor):
    EventRegistration = apps.get_model('events', 'EventRegistration')
    for reg in EventRegistration.objects.select_related('ticket_type').all():
        if reg.ticket_type and reg.ticket_type.price is not None:
            reg.booking_price = reg.ticket_type.price
            reg.save(update_fields=['booking_price'])


def reverse_populate(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_event_options_event_last_payment_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='booking_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Der zum Zeitpunkt der Buchung gültige Preis, unbeeinflusst von späteren Preisänderungen.', max_digits=6, null=True, verbose_name='Vereinbarter Ticketpreis (€)'),
        ),
        migrations.RunPython(populate_booking_price, reverse_populate),
    ]
