# Generated by Django 6.0.7 on 2026-10-01 07:26

import django.db.models.deletion
import knowledge.storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0014_eventregistration_booking_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('content', models.TextField(blank=True, verbose_name='Inhalt')),
                ('search_text', models.TextField(blank=True, editable=False)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='knowledge.knowledgepage', verbose_name='Übergeordnete Seite')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wissensseite',
                'verbose_name_plural': 'Wissensseiten',
                'ordering': ['order', 'title', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=300, storage=knowledge.storage.private_storage, upload_to=knowledge.storage.attachment_path)),
                ('original_name', models.CharField(max_length=200)),
                ('size', models.PositiveIntegerField()),
                ('mime_type', models.CharField(default='application/octet-stream', max_length=80)),
                ('is_image', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='knowledge.knowledgepage')),
            ],
            options={
                'verbose_name': 'Interner Anhang',
                'verbose_name_plural': 'Interne Anhänge',
                'ordering': ['original_name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('search_text', models.TextField(blank=True)),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Änderungsnotiz')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='knowledge.knowledgepage')),
            ],
            options={
                'verbose_name': 'Seitenversion',
                'verbose_name_plural': 'Seitenversionen',
                'ordering': ['-number'],
            },
        ),
        migrations.AddField(
            model_name='knowledgepage',
            name='published_revision',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='knowledge.knowledgerevision'),
        ),
        migrations.CreateModel(
            name='KnowledgeSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Bereich')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Beschreibung')),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_spaces', to='events.event', verbose_name='Veranstaltung')),
            ],
            options={
                'verbose_name': 'Wissensbereich',
                'verbose_name_plural': 'Wissensbereiche',
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='knowledgepage',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='knowledge.knowledgespace', verbose_name='Bereich'),
        ),
        migrations.AddConstraint(
            model_name='knowledgerevision',
            constraint=models.UniqueConstraint(fields=('page', 'number'), name='knowledge_unique_revision'),
        ),
    ]
