# Generated by Django 6.0.7 on 2026-07-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-is_pinned', '-created_at'], 'verbose_name': 'News-Beitrag', 'verbose_name_plural': 'News-Beiträge'},
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Wichtige Durchsage/Ankündigung oben auf dem Dashboard fixieren.', verbose_name='Angepinnt (Sticky Banner)'),
        ),
    ]
