# Generated by Django 6.0.7 on 2026-08-16 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsarticle_options_newsarticle_is_pinned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-is_pinned', '-created_at', '-id'], 'verbose_name': 'News-Beitrag', 'verbose_name_plural': 'News-Beiträge'},
        ),
    ]
