# Generated by Django 6.0.7 on 2026-10-05 05:03

import django.core.validators
import news.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newsarticle_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Optionales Vorschaubild. JPG, PNG oder WebP, maximal 10 MB. Fotos idealerweise im Querformat.', upload_to='news/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), news.images.validate_news_image_size], verbose_name='Titelbild'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='cover_image_alt',
            field=models.CharField(blank=True, help_text='Beschreibe den Bildinhalt für Besucher mit Screenreader.', max_length=250, verbose_name='Bildbeschreibung'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='image_fit',
            field=models.CharField(choices=[('cover', 'Foto: Vorschau proportional zuschneiden'), ('contain', 'Flyer: Bild vollständig anzeigen')], default='cover', help_text='Gilt auch für die Vorschau eines vorhandenen Bildes im Artikeltext.', max_length=10, verbose_name='Bilddarstellung'),
        ),
    ]
