CONTACT_TEXTS = {
    'contact_title': 'Kontakt',
    'contact_eyebrow': 'Das Orga-Team erreichen',
    'contact_intro': 'Du hast eine Frage zur Veranstaltung? Wähle ein Thema und schreib uns eine Nachricht.',
    'contact_email_label': 'Deine E-Mail-Adresse',
    'contact_email_help': 'An diese Adresse kann dir das Orga-Team antworten.',
    'contact_category_label': 'Betreff',
    'contact_category_empty': 'Bitte ein Thema auswählen',
    'contact_message_label': 'Nachricht',
    'contact_message_help': 'Maximal 10.000 Zeichen.',
    'contact_send': 'Nachricht senden',
    'contact_privacy_notice': 'Wir verwenden deine E-Mail-Adresse und Nachricht zur Bearbeitung deiner Anfrage.',
    'contact_privacy_link': 'Informationen zum Datenschutz',
    'contact_success': 'Deine Anfrage wurde angenommen und wird per E-Mail an das Orga-Team weitergeleitet.',
    'contact_unavailable': 'Das Kontaktformular ist momentan nicht verfügbar. Bitte versuche es später erneut.',
    'contact_required': 'Bitte fülle dieses Feld aus.',
    'contact_invalid_email': 'Bitte gib eine gültige E-Mail-Adresse ein.',
    'contact_invalid_category': 'Dieses Thema ist nicht mehr verfügbar. Bitte wähle ein anderes Thema.',
    'contact_message_too_long': 'Die Nachricht darf höchstens 10.000 Zeichen enthalten.',
    'contact_invalid_token': 'Das Formular ist abgelaufen oder wurde in einer anderen Sitzung geöffnet. Bitte lade die Seite neu.',
    'contact_spam_error': 'Die Anfrage konnte nicht angenommen werden. Bitte lade die Seite neu.',
    'contact_rate_limit': 'Du hast bereits mehrere Anfragen gesendet. Bitte warte eine Weile, bevor du es erneut versuchst.',
    'contact_ip_rate_limit': 'Es gehen gerade zu viele Anfragen ein. Bitte versuche es in einigen Minuten erneut.',
    'contact_error_summary': 'Bitte prüfe deine Angaben.',
    'contact_back_home': 'Zur Übersicht',
}
