TEXTS = {
    'clan_seat_button': 'Sitzplätze für Clan vormerken',
    'clan_seat_tooltip': 'Vorgemerkt für Clan {clan}',
    'clan_seat_disabled': 'Clan-Sitzplatzvormerkungen sind derzeit deaktiviert oder für diesen Clan gesperrt.',
    'clan_seat_permission': 'Nur aktive Clan-Admins dürfen Plätze für ihren Clan vormerken.',
    'clan_seat_event': 'Für diese Veranstaltung sind keine Clan-Vormerkungen möglich.',
    'clan_seat_expired': 'Die Vormerkungsfrist deines Clans für diese Veranstaltung ist abgelaufen.',
    'clan_seat_conflict': 'Mindestens ein ausgewählter Platz ist inzwischen belegt, gesperrt oder für einen anderen Clan vorgemerkt. Bitte aktualisiere die Auswahl.',
    'clan_seat_limit': 'Die Auswahl überschreitet das verfügbare Clan-Kontingent.',
    'clan_seat_stale': 'Die Clan-Vormerkungen oder Buchungen haben sich inzwischen geändert. Bitte aktualisiere den Sitzplan und prüfe die Auswahl erneut.',
    'clan_seat_invalid': 'Bitte eine gültige Auswahl unterschiedlicher Sitzplätze übermitteln.',
    'clan_seat_members_only': 'Dieser Sitzplatz ist für Clan {clan} vorgemerkt. Nur bestätigte Mitglieder dieses Clans dürfen ihn reservieren.',
    'clan_seat_saved': 'Die Clan-Vormerkungen wurden gespeichert.',
    'clan_seat_confirm': 'Bestätigen',
    'clan_seat_counter': 'Kontingent: {limit} · Übernommen: {claimed} · Ausgewählt: {selected} · Verfügbar: {remaining}',
    'clan_seat_until': 'Vormerkung gültig bis: {date}',
    'clan_seat_hint': 'Freie Plätze per Klick auswählen. Eigene offene Vormerkungen per Klick abwählen. Änderungen verlängern die Frist nicht.',
    'clan_seat_refresh': 'Aktualisieren',
    'clan_seat_legend': 'Für Clan vorgemerkt',
    'clan_seat_back': 'Zum Clanprofil',
    'clan_seat_network': 'Die Änderung konnte nicht bestätigt werden. Bitte den Sitzplan aktualisieren.',
}
