TEXTS = {
    'clan_payment_title': 'Clan-Sammelzahlung',
    'clan_payment_manage': 'Clan-Sammelzahlung und Plätze verwalten',
    'clan_payment_create': 'Zahlungsauftrag verbindlich erstellen',
    'clan_payment_confirm_lock': 'Ich bestätige, dass dieser Zahlungsauftrag und die enthaltenen Sitzplatzvormerkungen anschließend durch Clanadmins nicht mehr geändert werden können.',
    'clan_payment_confirmation_required': 'Bitte die verbindliche Aktion ausdrücklich bestätigen.',
    'clan_payment_locked': 'Die Clanplätze sind durch einen Sammelauftrag festgeschrieben. Bitte die Clan-Sammelzahlung öffnen.',
    'clan_payment_ticket_missing': 'Die Orga muss eine aktive Ticketkategorie für diese Veranstaltung festlegen. Bei genau einer aktiven Kategorie wird diese automatisch verwendet.',
    'clan_payment_ticket_price': 'Für eine Überweisung muss die Ticketkategorie einen Preis größer als null haben.',
    'clan_payment_no_seats': 'Bitte zuerst freie Sitzplätze für den Clan vormerken. Persönlich übernommene Plätze gehören nicht zur Sammelzahlung.',
    'clan_payment_short_deadline': 'Die verbleibende Vormerkfrist reicht für die Zahlungs- und Prüfzeit nicht aus. Bitte wende dich an die Orga.',
    'clan_payment_bank_missing': 'Die Orga muss zunächst vollständige Zahlungsdaten hinterlegen.',
    'clan_payment_stale': 'Die Plätze, Zahlungsdaten oder Ticketpreise haben sich geändert oder die Vorschau ist abgelaufen. Bitte die Übersicht neu öffnen.',
    'clan_payment_capacity': 'Die Veranstaltung hat nicht genügend freie Teilnehmerkapazität für diese Änderung.',
    'clan_payment_created': 'Der Zahlungsauftrag wurde erstellt. Bitte den Betrag rechtzeitig mit der angegebenen Referenz überweisen.',
    'clan_payment_pending': 'Zahlung ausstehend',
    'clan_payment_review_hint': 'Die Zahlungsfrist ist vorbei. Bitte keine neue Überweisung auf diesen Auftrag tätigen. Die Orga kann einen rechtzeitig eingegangenen Betrag noch innerhalb der angezeigten Prüfzeit bestätigen.',
    'clan_payment_paid': 'Bezahlt',
    'clan_payment_paid_hint': 'Die Zahlung ist bestätigt. Diese Plätze bleiben unabhängig von der bisherigen Vormerk- und Zahlungsfrist für den Clan geschützt.',
    'clan_payment_cancel_confirm': 'Stornierung dieses offenen Auftrags und Freigabe seiner Plätze ausdrücklich bestätigen.',
    'clan_payment_cancelled': 'Storniert',
    'clan_payment_count': 'Sitzplätze',
    'clan_payment_ticket': 'Ticketkategorie',
    'clan_payment_unit_price': 'Preis pro Platz',
    'clan_payment_total': 'Gesamtbetrag',
    'clan_payment_reference': 'Verwendungszweck',
    'clan_payment_due': 'Zahlungseingang spätestens am',
    'clan_payment_release': 'Automatische Freigabe ohne bestätigte Zahlung am',
    'clan_payment_deadline_hint': 'Alle Zeiten gelten in Europe/Vienna. Die Fristen werden nicht verlängert. Spätere Zahlungen müssen mit der Orga geklärt werden.',
    'clan_payment_preview_hint': 'Der Auftrag umfasst alle aktuell offenen Clanvormerkungen. Bereits persönlich übernommene Plätze bleiben separat. Anzahl, Preis und Plätze werden verbindlich festgeschrieben.',
    'clan_payment_assignment_hint': 'Mitglieder können nach Zahlungsbestätigung zugewiesen werden. Beim Ersetzen wird die bisherige Anmeldung wiederhergestellt; neu durch den Clan angemeldete Gäste werden abgemeldet. Bereits eingecheckte Gäste können nur durch die Orga geändert werden.',
    'clan_payment_managed_hint': 'Dieser Platz und seine Zahlungsdeckung werden über die Clan-Sammelzahlung verwaltet.',
    'clan_payment_not_paid': 'Mitglieder können erst nach der Zahlungsbestätigung zugewiesen werden.',
    'clan_payment_member_invalid': 'Bitte ein bestätigtes, aktives und nicht gesperrtes Clanmitglied auswählen.',
    'clan_payment_already_paid': 'Dieser Gast ist bereits bezahlt oder durch einen anderen Clanplatz gedeckt. Bitte mit der Orga klären.',
    'clan_payment_ticket_mismatch': 'Die vorhandene Anmeldung hat eine andere Ticketkategorie oder einen abweichenden Preis. Bitte mit der Orga klären.',
    'clan_payment_checked_in': 'Ein bereits eingecheckter Gast kann nur durch die Orga mit Begründung neu zugewiesen werden.',
    'clan_payment_assign': 'Mitglied zuweisen / ersetzen',
    'clan_payment_unassign': 'Zuweisung entfernen',
    'clan_payment_assignment_confirm': 'Änderung der Platzzuweisung und Zahlungsdeckung sowie gegebenenfalls den Wechsel vom bisherigen Sitzplatz bestätigen.',
    'clan_payment_assigned': 'Platzzuweisung und Zahlungsdeckung wurden aktualisiert.',
    'clan_payment_unassigned': 'Die Zuweisung wurde entfernt. Der bezahlte Platz bleibt für den Clan verfügbar.',
    'clan_payment_unassigned_label': 'Noch kein Mitglied zugewiesen',
    'clan_payment_seat': 'Sitzplatz',
    'clan_payment_member': 'Clanmitglied',
    'clan_payment_confirm_received': 'Zahlungseingang bestätigen',
    'clan_payment_received_at': 'Tatsächlicher Zahlungseingang',
    'clan_payment_received_amount': 'Eingegangener Betrag (€)',
    'clan_payment_received_invalid': 'Bitte den vollständigen festgeschriebenen Betrag und einen Zahlungseingang zwischen Auftragserstellung und Zahlungsfrist angeben. Teilzahlungen und verspätete Zahlungen müssen separat mit der Orga geklärt werden.',
    'clan_payment_confirmed': 'Der Zahlungseingang wurde bestätigt. Die Plätze sind jetzt bezahlt.',
    'clan_payment_expired': 'Der Zahlungsauftrag ist abgelaufen oder storniert. Spätere Zahlungen müssen mit der Orga geklärt werden.',
    'clan_payment_cancel': 'Offenen Zahlungsauftrag stornieren und Plätze freigeben',
    'clan_payment_reason': 'Begründung',
    'clan_payment_reason_required': 'Für diese Orga-Korrektur ist eine Begründung erforderlich.',
    'clan_payment_cancel_success': 'Der Zahlungsauftrag wurde storniert und seine Plätze wurden freigegeben.',
    'clan_payment_expiry_reason': 'Keine Zahlungsbestätigung innerhalb der festgeschriebenen Frist.',
    'clan_payment_event_reason': 'Die Veranstaltung wurde beendet, abgesagt oder deaktiviert.',
    'clan_payment_clan_delete_blocked': 'Dieser Clan hat dokumentierte Sammelzahlungen. Bitte die Auflösung zuerst mit der Orga klären.',
    'clan_payment_received_confirm': 'Zahlungseingang, Betrag und Referenz geprüft und die Bestätigung ausdrücklich freigeben.',
    'clan_payment_admin_confirm': 'Zahlungsauftrag bestätigen oder korrigieren',
    'clan_payment_paid_tooltip': 'Bezahlt für Clan {clan}; Zuweisung durch Clanadmins',
    'clan_payment_pending_tooltip': 'Sammelzahlung für Clan {clan} ausstehend; Plätze festgeschrieben',
    'clan_payment_legend_pending': 'Clan-Zahlung ausstehend',
    'clan_payment_legend_paid': 'Clanplatz bezahlt',
    'clan_payment_account_blocked': 'Du bist das letzte aktive Mitglied eines Clans mit Sammelzahlungen. Bitte kläre die Verwaltung zuerst mit der Orga.',
}
