# Generated by Django 6.0.7 on 2026-08-12 21:18

import django.db.models.deletion
import tournaments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0006_alter_eventregistration_checkin_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Spielname')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL-Slug')),
                ('mode', models.CharField(blank=True, help_text='z. B. 5v5 Bomb Scenario, 1v1 Aim Map, Deathmatch', max_length=100, verbose_name='Spielmodus')),
                ('team_size', models.PositiveIntegerField(default=5, help_text='Anzahl der Spieler pro Team (1 = Einzelspieler / Solo)', verbose_name='Teamgröße')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='game_logos/', verbose_name='Spiellogo')),
                ('rules', models.TextField(blank=True, verbose_name='Regeln & Einstellungen')),
                ('additional_info', models.TextField(blank=True, verbose_name='Zusätzliche Informationen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zuletzt geändert')),
            ],
            options={
                'verbose_name': 'Spiel',
                'verbose_name_plural': 'Spiele',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Teamname')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL-Slug')),
                ('tag', models.CharField(blank=True, max_length=10, verbose_name='Clan-/Team-Tag')),
                ('invite_code', models.CharField(default=tournaments.models.generate_invite_code, help_text='Code für direkten Beitritt weiterer Teammitglieder', max_length=12, unique=True, verbose_name='Einladungscode')),
                ('is_solo', models.BooleanField(default=False, help_text='Automatisch erstelltes Solo-Team für 1v1 Turniere', verbose_name='Einzelspieler-Team')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zuletzt geändert')),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captain_teams', to=settings.AUTH_USER_MODEL, verbose_name='Kapitän')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournaments.game', verbose_name='Spiel')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Turniertitel')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True, verbose_name='URL-Slug')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung / Preise')),
                ('mode', models.CharField(choices=[('SINGLE_ELIMINATION', 'Single Elimination (KO-System)'), ('DOUBLE_ELIMINATION', 'Double Elimination (Winner + Loser Bracket)'), ('LEAGUE', 'Liga (Jeder gegen Jeden)'), ('GROUP_STAGE', 'Gruppenspiele mit anschließendem KO-System'), ('FFA', 'Alle in einem (Free-For-All / Deathmatch)')], default='SINGLE_ELIMINATION', max_length=30, verbose_name='Turniermodus')),
                ('max_teams', models.PositiveIntegerField(default=16, verbose_name='Max. Teams / Teilnehmer')),
                ('registration_start', models.DateTimeField(verbose_name='Anmeldebeginn')),
                ('registration_end', models.DateTimeField(verbose_name='Anmeldeschluss')),
                ('status', models.CharField(choices=[('DRAFT', 'Entwurf'), ('OPEN', 'Anmeldung geöffnet'), ('CLOSED', 'Anmeldung geschlossen'), ('IN_PROGRESS', 'Turnier läuft'), ('FINISHED', 'Beendet'), ('CANCELLED', 'Abgesagt')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('is_generated', models.BooleanField(default=False, help_text='Zeigt an, ob der Turnierbaum für dieses Turnier offiziell generiert wurde.', verbose_name='Turnierbaum generiert')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zuletzt geändert')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='events.event', verbose_name='Veranstaltung')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='tournaments.game', verbose_name='Spiel')),
                ('tournament_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_tournaments', to=settings.AUTH_USER_MODEL, verbose_name='Turnieradmin')),
                ('tournament_support', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supported_tournaments', to=settings.AUTH_USER_MODEL, verbose_name='Turniersupport')),
            ],
            options={
                'verbose_name': 'Turnier',
                'verbose_name_plural': 'Turniere',
                'ordering': ['-registration_start', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(default=1, verbose_name='Runde')),
                ('match_number', models.PositiveIntegerField(default=1, verbose_name='Match-Nummer in Runde')),
                ('bracket_type', models.CharField(choices=[('WINNERS', 'Winner Bracket'), ('LOSERS', 'Loser Bracket'), ('FINAL', 'Finale'), ('GROUP', 'Gruppenspiel'), ('FFA', 'Free For All')], default='WINNERS', max_length=15, verbose_name='Bracket Typ')),
                ('group_name', models.CharField(blank=True, max_length=20, verbose_name='Gruppe (für Gruppenspiele)')),
                ('score_team1', models.IntegerField(blank=True, null=True, verbose_name='Ergebnis Team 1')),
                ('score_team2', models.IntegerField(blank=True, null=True, verbose_name='Ergebnis Team 2')),
                ('is_bye', models.BooleanField(default=False, verbose_name='Freilos (BYE)')),
                ('status', models.CharField(choices=[('PENDING', 'Ausstehend'), ('READY', 'Bereit'), ('IN_PROGRESS', 'Läuft'), ('COMPLETED', 'Beendet')], default='PENDING', max_length=15, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_matches', to='tournaments.team', verbose_name='Verlierer')),
                ('next_match_loser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_matches_loser', to='tournaments.tournamentmatch', verbose_name='Folgematch Verlierer')),
                ('next_match_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_matches_winner', to='tournaments.tournamentmatch', verbose_name='Folgematch Sieger')),
                ('team1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_team1', to='tournaments.team', verbose_name='Team 1')),
                ('team2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_team2', to='tournaments.team', verbose_name='Team 2')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament', verbose_name='Turnier')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='tournaments.team', verbose_name='Gewinner')),
            ],
            options={
                'verbose_name': 'Turnier-Match',
                'verbose_name_plural': 'Turnier-Matches',
                'ordering': ['bracket_type', 'round_number', 'match_number'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CAPTAIN', 'Kapitän'), ('MEMBER', 'Mitglied')], default='MEMBER', max_length=10, verbose_name='Rolle')),
                ('status', models.CharField(choices=[('ACCEPTED', 'Mitglied'), ('PENDING', 'Anfrage ausstehend')], default='ACCEPTED', max_length=10, verbose_name='Status')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Beigetreten am')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tournaments.team', verbose_name='Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Team-Mitgliedschaft',
                'verbose_name_plural': 'Team-Mitgliedschaften',
                'ordering': ['role', 'joined_at'],
                'unique_together': {('team', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TournamentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Angemeldet am')),
                ('seed', models.PositiveIntegerField(blank=True, null=True, verbose_name='Seed / Platzierung')),
                ('group_name', models.CharField(blank=True, max_length=20, verbose_name='Gruppe (z.B. Gruppe A)')),
                ('score', models.IntegerField(default=0, verbose_name='Punkte / Kills (für FFA)')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_registrations', to='tournaments.team', verbose_name='Team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournaments.tournament', verbose_name='Turnier')),
            ],
            options={
                'verbose_name': 'Turnieranmeldung',
                'verbose_name_plural': 'Turnieranmeldungen',
                'ordering': ['registered_at'],
                'unique_together': {('tournament', 'team')},
            },
        ),
    ]
