# Generated by Django 6.0.7 on 2026-08-15 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventregistration_cancelled_at_and_more'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Die Veranstaltung, für die dieses Team aktuell antritt.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='events.event', verbose_name='Veranstaltung'),
        ),
        migrations.AddField(
            model_name='team',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Zeigt an, ob das Team aus einer früheren Veranstaltung archiviert wurde.', verbose_name='Archiviert'),
        ),
    ]
