# Generated by Django 6.0.7 on 2026-08-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_team_event_team_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='decision_reason',
            field=models.CharField(blank=True, help_text='Wird erfasst bei manueller Admin-Entscheidung, Disqualifikation oder Forfeit.', max_length=255, verbose_name='Entscheidungsgrund'),
        ),
    ]
