# Generated by Django 6.0.7 on 2026-08-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournamentmatch_decision_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='next_match_loser_slot',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Team 1'), (2, 'Team 2')], default=1, help_text='1 für Team 1 Slot, 2 für Team 2 Slot im Verlierer-Folgematch', verbose_name='Ziel-Slot Verlierer'),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='next_match_winner_slot',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Team 1'), (2, 'Team 2')], default=1, help_text='1 für Team 1 Slot, 2 für Team 2 Slot im Sieger-Folgematch', verbose_name='Ziel-Slot Sieger'),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='bracket_type',
            field=models.CharField(choices=[('WINNERS', 'Winner Bracket'), ('LOSERS', 'Loser Bracket'), ('GRAND_FINAL', 'Grand Final'), ('GRAND_FINAL_RESET', 'Grand Final Reset'), ('FINAL', 'Finale'), ('GROUP', 'Gruppenspiel'), ('FFA', 'Free For All')], default='WINNERS', max_length=20, verbose_name='Bracket Typ'),
        ),
    ]
