# Generated by Django 6.0.7 on 2026-08-17 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_tournamentmatch_next_match_loser_slot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentMatchParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(blank=True, help_text='1 für 1. Platz, 2 für 2. Platz, etc.', null=True, verbose_name='Platzierung')),
                ('score', models.IntegerField(default=0, verbose_name='Punkte / Kills / Zeit')),
                ('is_disqualified', models.BooleanField(default=False, verbose_name='Disqualifiziert')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notizen / Details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournaments.tournamentmatch', verbose_name='Match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_participations', to='tournaments.team', verbose_name='Team / Teilnehmer')),
            ],
            options={
                'verbose_name': 'Match-Teilnehmer (FFA)',
                'verbose_name_plural': 'Match-Teilnehmer (FFA)',
                'ordering': ['rank', '-score', 'id'],
                'unique_together': {('match', 'team')},
            },
        ),
    ]
