# Generated by Django 6.0.7 on 2026-09-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_tournamentmatchparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentregistration',
            name='is_forfeited',
            field=models.BooleanField(default=False, help_text='Wird auf True gesetzt, wenn das Team das Turnier aufgibt oder vorzeitig ausscheidet.', verbose_name='Aufgegeben / Zurückgezogen'),
        ),
    ]
