# Generated by Django 6.0.7 on 2026-09-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_tournamentregistration_is_forfeited'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournament_start',
            field=models.DateTimeField(blank=True, help_text='Beginn des Turniers. Bleibt dieses Feld leer, gilt automatisch das Ende des Anmeldeschlusses.', null=True, verbose_name='Turnierstart'),
        ),
    ]
