# Generated by Django 6.0.7 on 2026-09-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_tournament_tournament_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Teamname'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tag',
            field=models.CharField(blank=True, max_length=5, verbose_name='Clan-/Team-Tag'),
        ),
    ]
