# Generated by Django 6.0.7 on 2026-10-01 04:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_alter_team_name_alter_team_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SwissRoundEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='swiss_allow_draws',
            field=models.BooleanField(default=False, verbose_name='Schweizer System: Unentschieden erlauben'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='swiss_pairing_seed',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='swiss_rounds',
            field=models.PositiveSmallIntegerField(default=4, help_text='Vor dem Start festlegen. Bei gerader Teilnehmerzahl höchstens N−1, bei ungerader höchstens N Runden.', verbose_name='Schweizer System: Runden'),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='result_type',
            field=models.CharField(choices=[('PLAYED', 'Gespielt'), ('BYE', 'Freilos'), ('WALKOVER', 'Kampfloser Sieg'), ('DOUBLE_FORFEIT', 'Beide Teilnehmer zurückgezogen')], default='PLAYED', max_length=20, verbose_name='Ergebnisart'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='mode',
            field=models.CharField(choices=[('SINGLE_ELIMINATION', 'Single Elimination (KO-System)'), ('DOUBLE_ELIMINATION', 'Double Elimination (Winner + Loser Bracket)'), ('LEAGUE', 'Liga (Jeder gegen Jeden)'), ('GROUP_STAGE', 'Gruppenspiele mit anschließendem KO-System'), ('FFA', 'Alle in einem (Free-For-All / Deathmatch)'), ('SWISS', 'Schweizer System')], default='SINGLE_ELIMINATION', max_length=30, verbose_name='Turniermodus'),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='bracket_type',
            field=models.CharField(choices=[('WINNERS', 'Winner Bracket'), ('LOSERS', 'Loser Bracket'), ('GRAND_FINAL', 'Grand Final'), ('GRAND_FINAL_RESET', 'Grand Final Reset'), ('FINAL', 'Finale'), ('GROUP', 'Gruppenspiel'), ('FFA', 'Free For All'), ('SWISS', 'Schweizer Runde')], default='WINNERS', max_length=20, verbose_name='Bracket Typ'),
        ),
        migrations.CreateModel(
            name='SwissRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Runde')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Veröffentlicht am')),
                ('input_digest', models.CharField(max_length=64)),
                ('standings_snapshot', models.JSONField(default=list)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swiss_round_records', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='swiss_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.swissround'),
        ),
        migrations.AddConstraint(
            model_name='tournamentmatch',
            constraint=models.UniqueConstraint(condition=models.Q(('bracket_type', 'SWISS')), fields=('tournament', 'round_number', 'match_number'), name='unique_swiss_match_number'),
        ),
        migrations.AddField(
            model_name='swissroundentry',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swiss_entries', to='tournaments.tournamentmatch'),
        ),
        migrations.AddField(
            model_name='swissroundentry',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='swiss_entries', to='tournaments.tournamentregistration'),
        ),
        migrations.AddField(
            model_name='swissroundentry',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tournaments.swissround'),
        ),
        migrations.AddField(
            model_name='swissroundentry',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='swiss_entries', to='tournaments.team'),
        ),
        migrations.AddConstraint(
            model_name='swissround',
            constraint=models.UniqueConstraint(fields=('tournament', 'number'), name='unique_swiss_round'),
        ),
        migrations.AddConstraint(
            model_name='swissroundentry',
            constraint=models.UniqueConstraint(fields=('round', 'team'), name='unique_swiss_round_team'),
        ),
    ]
