# Generated by Django 6.0.7 on 2026-10-01 18:34

from django.db import migrations, models


def preserve_existing_tiebreaks(apps, schema_editor):
    # Existing tournaments retain the rule announced when they were created.
    apps.get_model('tournaments', 'Tournament').objects.using(schema_editor.connection.alias).update(standings_tiebreak='LEGACY')


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_swissroundentry_tournament_swiss_allow_draws_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='swissround',
            name='repeat_pairings_approved',
            field=models.BooleanField(default=False, verbose_name='Wiederholungen ausdrücklich freigegeben'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='group_qualifiers_per_group',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Automatisch (ab 8 Teams zwei pro Gruppe)'), (1, 'Ein Team pro Gruppe'), (2, 'Zwei Teams pro Gruppe')], default=0, verbose_name='Qualifikanten pro Gruppe'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='play_third_place',
            field=models.BooleanField(default=False, help_text='Bei Single Elimination und Gruppenphase mit Halbfinals.', verbose_name='Spiel um Platz 3'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='standings_tiebreak',
            field=models.CharField(choices=[('LEGACY', 'Punkte, Score-Differenz, Scores, Teamname'), ('SHARED', 'Punkte, Score-Differenz, Scores; geteilte Plätze'), ('HEAD_TO_HEAD', 'Punkte, direkter Vergleich, Score; geteilte Plätze')], default='SHARED', help_text='In Gruppen entscheidet bei weiterem Gleichstand die Setzposition über die Qualifikation.', max_length=20, verbose_name='Gleichstandsregel für Liga und Gruppen'),
        ),
        migrations.RunPython(preserve_existing_tiebreaks, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='bracket_type',
            field=models.CharField(choices=[('WINNERS', 'Winner Bracket'), ('LOSERS', 'Loser Bracket'), ('GRAND_FINAL', 'Grand Final'), ('GRAND_FINAL_RESET', 'Grand Final Reset'), ('FINAL', 'Finale'), ('THIRD_PLACE', 'Spiel um Platz 3'), ('GROUP', 'Gruppenspiel'), ('FFA', 'Free For All'), ('SWISS', 'Schweizer Runde')], default='WINNERS', max_length=20, verbose_name='Bracket Typ'),
        ),
    ]
