# Generated by Django 6.0.7 on 2026-10-02 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_format_improvements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='restart_cancelled_source',
            field=models.BooleanField(default=False, editable=False, verbose_name='Original beim Neustart abgesagt'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='restart_reason',
            field=models.TextField(blank=True, editable=False, max_length=1000, verbose_name='Anlass für den Neustart'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='restart_request_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='restart_source_title',
            field=models.CharField(blank=True, editable=False, max_length=150, verbose_name='Originaltitel beim Neustart'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='restart_team_snapshot',
            field=models.JSONField(blank=True, default=list, editable=False, verbose_name='Übernommene Teams beim Neustart'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='restarted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restarted_tournaments', to=settings.AUTH_USER_MODEL, verbose_name='Neustart vorbereitet von'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='restarted_from',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restart_editions', to='tournaments.tournament', verbose_name='Neustart von'),
        ),
    ]
