# Generated by Django 6.0.7 on 2026-10-03 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_eventregistration_booking_price'),
        ('tournaments', '0011_tournament_restart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='added_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_team_additions', to=settings.AUTH_USER_MODEL, verbose_name='Hinzugefügt von'),
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Offen'), ('ACCEPTED', 'Angenommen'), ('DECLINED', 'Abgelehnt'), ('WITHDRAWN', 'Zurückgezogen'), ('EXPIRED', 'Ungültig geworden')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_invitations', to='events.event', verbose_name='Veranstaltung bei Einladung')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_team_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Eingeladen von')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tournaments.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Eingeladener Spieler')),
            ],
            options={
                'verbose_name': 'Team-Einladung',
                'verbose_name_plural': 'Team-Einladungen',
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('team', 'user'), name='unique_pending_team_invitation')],
            },
        ),
    ]
