# Generated by Django 6.0.7 on 2026-10-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_team_invitations'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='roster_rule',
            field=models.CharField(choices=[('STRICT', 'Vollständiges Team erforderlich'), ('BY_START', 'Team darf bis zum Start aufgefüllt werden'), ('ALLOW_INCOMPLETE', 'Unvollständige Teams zugelassen')], default='STRICT', help_text='Gilt für Anmeldung und Start. Die maximale Teamgröße bleibt bestehen; nach Turniergenerierung ist die Regel gesperrt.', max_length=20, verbose_name='Regel zur Teamgröße'),
        ),
    ]
