# Generated by Django 6.0.7 on 2026-10-07 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_existing_playoffs(apps, schema_editor):
    Tournament = apps.get_model('tournaments', 'Tournament')
    Match = apps.get_model('tournaments', 'TournamentMatch')
    # Existing populated playoffs have already been presented to participants.
    # Keep their qualification frozen; do not invent a confirmation actor/time.
    ids = Match.objects.filter(tournament__mode='GROUP_STAGE', bracket_type='FINAL',
                               team1__isnull=False).values('tournament_id')
    Tournament.objects.filter(pk__in=ids).update(playoffs_released_at=models.F('updated_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_tournament_roster_rule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='playoffs_released_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='results_confirmed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='results_confirmed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_tournaments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Entwurf'), ('OPEN', 'Anmeldung geöffnet'), ('CLOSED', 'Anmeldung geschlossen'), ('IN_PROGRESS', 'Turnier läuft'), ('RESULTS_REVIEW', 'Ergebnisse prüfen'), ('FINISHED', 'Beendet'), ('CANCELLED', 'Abgesagt')], default='DRAFT', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='TournamentResultLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_label', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(default='RESULT', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_logs', to='tournaments.tournamentmatch')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_logs', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Ergebnisprotokoll',
                'verbose_name_plural': 'Ergebnisprotokolle',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.RunPython(preserve_existing_playoffs, migrations.RunPython.noop),
    ]
