# Generated by Django 6.0.7 on 2026-10-08 07:39

import django.db.models.deletion
import tournaments.external_urls
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_eventregistration_booking_price'),
        ('tournaments', '0014_tournament_playoffs_released_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Turniertitel')),
                ('provider_name', models.CharField(max_length=100, verbose_name='Anbietername')),
                ('external_url', models.URLField(max_length=1000, validators=[tournaments.external_urls.validate_external_tournament_url], verbose_name='Turnieradresse')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Kurzbeschreibung')),
                ('mode', models.CharField(blank=True, max_length=100, verbose_name='Turniermodus')),
                ('tournament_start', models.DateTimeField(blank=True, null=True, verbose_name='Turnierstart')),
                ('registration_end', models.DateTimeField(blank=True, null=True, verbose_name='Anmeldeschluss')),
                ('status', models.CharField(choices=[('DRAFT', 'Entwurf'), ('PUBLISHED', 'Veröffentlicht')], default='DRAFT', max_length=10, verbose_name='Veröffentlichungszustand')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zuletzt geändert')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_tournaments', to='events.event', verbose_name='Veranstaltung')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_tournaments', to='tournaments.game', verbose_name='Spiel')),
            ],
            options={
                'verbose_name': 'Externes Turnier',
                'verbose_name_plural': 'Externe Turniere',
                'ordering': ('title', 'pk'),
            },
        ),
    ]
