# Generated by Django 6.0.7 on 2026-10-08 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0007_alter_clan_seat_limit_override'),
        ('tournaments', '0015_external_tournament'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentregistration',
            name='draw_clan',
            field=models.ForeignKey(blank=True, help_text='Von der Turnierleitung bestätigte Clan-Zuordnung für dieses Turnier.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_draw_registrations', to='clans.clan', verbose_name='Clan für die Auslosung'),
        ),
        migrations.CreateModel(
            name='TournamentDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(editable=False, unique=True)),
                ('mode', models.CharField(max_length=30)),
                ('method', models.CharField(max_length=20)),
                ('random_seed', models.PositiveIntegerField()),
                ('respect_seeds', models.BooleanField(default=True)),
                ('avoid_clans', models.BooleanField(default=True)),
                ('input_digest', models.CharField(max_length=64)),
                ('snapshot', models.JSONField(default=dict)),
                ('conflict_count', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draw_logs', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Turnierauslosung',
                'verbose_name_plural': 'Turnierauslosungen',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
