# Generated by Django 6.0.7 on 2026-08-27 19:36

import django.core.validators
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0010_eventregistration_short_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name des Sponsors')),
                ('logo_typ', models.CharField(choices=[('logo', 'Quadratisches Logo'), ('banner', 'Rechteckiges Banner')], default='logo', help_text='Steuert die Darstellung: Logo (quadratisch mit Name) oder Banner (volle Breite)', max_length=20, verbose_name='Logo-Typ')),
                ('bild', models.ImageField(upload_to='sponsors/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'svg'])], verbose_name='Logo- oder Banner-Datei')),
                ('url', models.URLField(blank=True, help_text='Website des Sponsors (optional)', verbose_name='Website URL')),
                ('beschreibung', tinymce.models.HTMLField(blank=True, help_text='Beschreibungstext über den django-tinymce-Editor', verbose_name='Beschreibung')),
                ('aktiv_modus', models.CharField(choices=[('dauerhaft', 'Dauerhaft aktiv'), ('veranstaltung', 'An Veranstaltung gekoppelt'), ('datum', 'Bis zu einem bestimmten Datum'), ('inaktiv', 'Inaktiv')], default='dauerhaft', help_text='Steuert, wie der Sponsor aktiv/inaktiv geschaltet wird', max_length=20, verbose_name='Aktiv-Modus')),
                ('aktiv_bis', models.DateField(blank=True, help_text="Nur relevant, wenn Aktiv-Modus 'Bis Datum' gewählt ist. Am angegebenen Tag noch aktiv, danach inaktiv.", null=True, verbose_name='Aktiv bis (inklusive)')),
                ('rang', models.PositiveIntegerField(default=100, help_text='Je kleiner die Zahl, desto weiter oben in der Liste.', verbose_name='Rang / Reihenfolge')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True, verbose_name='Zuletzt geändert')),
                ('veranstaltung', models.ForeignKey(blank=True, help_text="Nur relevant, wenn Aktiv-Modus 'An Veranstaltung gekoppelt' gewählt ist", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsors', to='events.event', verbose_name='Verknüpfte Veranstaltung')),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsoren',
                'ordering': ['rang', 'erstellt_am', 'id'],
            },
        ),
    ]
