# Generated by Django 6.0.7 on 2026-08-27 20:05

import django.core.validators
import sponsors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='bild',
            field=models.ImageField(help_text='Logo- oder Banner-Datei. Erlaubte Formate: JPG, PNG, WebP, GIF, SVG. Maximale Dateigröße: 10 MB.', upload_to='sponsors/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'svg']), sponsors.models.validate_sponsor_image_file_size], verbose_name='Logo- oder Banner-Datei'),
        ),
    ]
