# Generated by Django 6.0.7 on 2026-09-25 20:00

import django.db.models.deletion
import django.core.validators
import media_designer.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0014_eventregistration_booking_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('kind', models.CharField(choices=[('BADGE', 'Teilnehmerbadge'), ('CERTIFICATE', 'Turnierurkunde')], max_length=20, verbose_name='Art')),
                ('paper_size', models.CharField(choices=[('A4', 'A4'), ('A6', 'A6'), ('A7', 'A7'), ('A8', 'A8')], max_length=2, verbose_name='Format')),
                ('background', models.ImageField(blank=True, upload_to='media_templates/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), media_designer.validators.validate_background_image], verbose_name='Hintergrundbild')),
                ('elements', models.JSONField(blank=True, default=list)),
                ('schema_version', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_templates', to='events.event', verbose_name='Veranstaltung')),
            ],
            options={
                'verbose_name': 'Medienvorlage',
                'verbose_name_plural': 'Medienvorlagen',
                'ordering': ['event__start_date', 'name'],
            },
        ),
    ]
