# Generated by Django 6.0.7 on 2026-09-26 09:38

import django.core.validators
import media_designer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_designer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Schriftname')),
                ('file', models.FileField(help_text='TTF, OTF oder WOFF2 bis 5 MB. Beim Löschen verwenden betroffene Vorlagenfelder die Standardschrift.', upload_to='media_fonts/', validators=[django.core.validators.FileExtensionValidator(['ttf', 'otf', 'woff2']), media_designer.validators.validate_font_file], verbose_name='Schriftdatei')),
            ],
            options={
                'verbose_name': 'Medienschrift',
                'verbose_name_plural': 'Medienschriften',
                'ordering': ['name'],
            },
        ),
    ]
