TEXTS = {
    'draw_prepare': 'Auslosung vorbereiten',
    'draw_title': 'Turnierbaum prüfen & auslosen',
    'draw_intro': 'Prüfe die Clan-Zuordnung und die Paarungen vor dem Start. Die Vorschau schließt die Anmeldung noch nicht. Erst die Freigabe übernimmt diese Auslosung verbindlich.',
    'draw_clan': 'Clan für diese Auslosung',
    'draw_no_clan': 'Kein Clan zugeordnet',
    'draw_clan_hint': 'Die Zuordnung gilt für dieses Turnier. Team-Tags und persönliche Clanmitgliedschaften werden dadurch nicht verändert.',
    'draw_suggestion': 'Vorschlag aus der Clanmitgliedschaft des Kapitäns: {clan}',
    'draw_suggestions': 'Clan-Vorschläge übernehmen',
    'draw_avoid_clans': 'Clan-interne Begegnungen in Runde 1 vermeiden',
    'draw_avoid_groups': 'Teams desselben Clans auf die Gruppen verteilen',
    'draw_respect_seeds': 'Gesetzte Teampositionen beibehalten',
    'draw_seed_hint': 'Teams mit einem Seed behalten ihre ursprüngliche Position. Deaktiviere diese Vorgabe ausdrücklich, um auch diese Teams neu zu verteilen.',
    'draw_apply': 'Vorgaben aktualisieren',
    'draw_shuffle': 'Neu auslosen',
    'draw_swap': 'Teampositionen tauschen',
    'draw_swap_first': 'Erstes Team',
    'draw_swap_second': 'Zweites Team',
    'draw_swap_hint': 'Wähle zwei Teams zum Tauschen. Danach werden die Vorschau und die Clan-Hinweise aktualisiert.',
    'draw_locked': 'gesetzt',
    'draw_seed': 'Seed',
    'draw_roster': 'Bestätigte Spieler',
    'draw_preview': 'Vorschau der verbindlichen Auslosung',
    'draw_positions': 'Startpositionen',
    'draw_conflicts': 'Clan-interne Begegnungen: {count}',
    'draw_group_conflicts': 'Clan-interne Begegnungen innerhalb der Gruppen: {count}',
    'draw_conflict_pair': '{team1} gegen {team2} · {clan}',
    'draw_conflict_hint': 'Diese Auslosung enthält Clan-Begegnungen. Freilose, gesetzte Positionen oder die Anzahl der Teams eines Clans können eine vollständige Trennung verhindern. Du kannst Teams tauschen oder die Vorgaben ändern.',
    'draw_approve': 'Ich bestätige die angezeigten Clan-Begegnungen.',
    'draw_reason': 'Begründung für die Freigabe mit Clan-Begegnungen',
    'draw_publish': 'Auslosung übernehmen & Turnier starten',
    'draw_publish_confirm': 'Diese Paarungen übernehmen, die Anmeldung schließen und das Turnier starten?',
    'draw_publish_yes': 'Ja, diese Auslosung starten',
    'draw_cancel': 'Abbrechen',
    'draw_refresh': 'Neue Vorschau öffnen',
    'draw_dirty': 'Die Vorgaben wurden geändert. Aktualisiere zuerst die Vorschau, damit die Freigabe die angezeigten Paarungen übernimmt.',
    'draw_success': 'Die geprüfte Auslosung wurde übernommen. Das Turnier läuft jetzt.',
    'draw_already_published': 'Diese Auslosung wurde bereits übernommen.',
    'draw_permission': 'Nur die Turnierleitung darf die Auslosung vorbereiten und freigeben.',
    'draw_unavailable': 'Die Auslosung kann nur vor dem Start bei geöffneter oder geschlossener Anmeldung vorbereitet werden.',
    'draw_invalid': 'Die Vorschau ist ungültig oder abgelaufen. Bitte öffne eine neue Vorschau.',
    'draw_stale': 'Teilnehmer, Kader oder Turniervorgaben haben sich seit der Vorschau geändert. Bitte öffne eine neue Vorschau und prüfe die Paarungen erneut.',
    'draw_invalid_teams': 'Die Auslosung muss jedes aktive angemeldete Team genau einmal enthalten.',
    'draw_invalid_clans': 'Bitte wähle gültige Clans für die angemeldeten Teams.',
    'draw_invalid_options': 'Die Auslosungsvorgaben sind ungültig.',
    'draw_duplicate_seeds': 'Die vorhandenen Seeds müssen eindeutig sein. Bitte korrigiere die Seeds vor der Auslosung.',
    'draw_seed_locked': 'Ein gesetztes Team kann bei aktiver Seed-Vorgabe seine Position nicht wechseln.',
    'draw_invalid_swap': 'Bitte wähle zwei verschiedene angemeldete Teams.',
    'draw_approval_required': 'Bitte bestätige die Clan-Begegnungen und gib eine Begründung an.',
    'draw_minimum': 'Für diesen Modus sind mindestens {count} aktive angemeldete Teams erforderlich.',
    'draw_history': 'Auslosungsprotokoll',
    'draw_history_empty': 'Für dieses Turnier wurde noch keine Auslosung über die Vorschau freigegeben.',
    'draw_method_standard': 'Vorhandene Setzreihenfolge',
    'draw_method_random': 'Neu ausgelost',
    'draw_method_manual': 'Manuell bearbeitet',
    'draw_first_round': 'Runde 1',
    'draw_group_a': 'Gruppe A',
    'draw_group_b': 'Gruppe B',
    'draw_matchday': 'Spieltag {number}',
    'draw_bye': 'Freilos',
    'draw_league_hint': 'Die Clan-Regel gilt für den ersten Spieltag. Im weiteren Ligaverlauf spielt jedes Team gegen jedes andere Team.',
    'draw_group_hint': 'Die Clan-Regel verteilt Teams möglichst gleichmäßig auf die beiden Gruppen. Die Qualifikation und die anschließenden K.-o.-Wege folgen den Turnierregeln.',
    'draw_swiss_hint': 'Hier wird Runde 1 vorbereitet. Weitere Schweizer Runden werden anhand der Ergebnisse über die bestehende Rundenvorschau freigegeben.',
    'draw_ffa_hint': 'Alle Teilnehmer spielen gemeinsam in einem FFA-Match. Prüfe hier Teilnehmer, Kader und Clan-Zuordnung vor dem Start.',
    'draw_admin_select_one': 'Bitte wähle genau ein Turnier, um seine Auslosung vorzubereiten.',
}
