TEXTS = {
    'external_tournament_badge': 'Extern',
    'external_tournament_provider': 'Anbieter: {provider}',
    'external_tournament_registration_hint': 'Anmeldung und Spielplan beim Anbieter',
    'external_tournament_open': 'Zum Turnier →',
    'external_tournament_link_unavailable': 'Link derzeit nicht verfügbar.',
    'external_tournament_datetime': '{date} Uhr',
    'external_tournament_status_draft': 'Entwurf',
    'external_tournament_status_published': 'Veröffentlicht',
    'external_tournament_field_event': 'Veranstaltung',
    'external_tournament_field_game': 'Spiel',
    'external_tournament_field_title': 'Turniertitel',
    'external_tournament_field_provider_name': 'Anbietername',
    'external_tournament_field_external_url': 'Turnieradresse',
    'external_tournament_field_description': 'Kurzbeschreibung',
    'external_tournament_field_mode': 'Turniermodus',
    'external_tournament_field_tournament_start': 'Turnierstart',
    'external_tournament_field_registration_end': 'Anmeldeschluss',
    'external_tournament_field_status': 'Veröffentlichungszustand',
    'external_tournament_url_help': 'Vollständige HTTPS-Adresse des Anbieters oder der konkreten Turnierseite. Der Button öffnet diese Adresse im selben Tab.',
    'external_tournament_description_help': 'Optionaler Kurztext mit höchstens 500 Zeichen. Angaben werden von der Orga gepflegt.',
    'external_tournament_mode_help': 'Optionaler Modus zur Anzeige auf der Turnierkarte, z. B. Schweizer System.',
    'external_tournament_status_help': 'Entwürfe sind nur für aktive Mitarbeiter sichtbar. Veröffentlicht zeigt den Eintrag allen Besuchern in der Übersicht des aktiven Events.',
    'external_tournament_url_invalid': 'Bitte eine gültige vollständige HTTPS-Adresse ohne Leerzeichen oder Steuerzeichen angeben.',
    'external_tournament_url_credentials': 'Zugangsdaten dürfen nicht in der Turnieradresse enthalten sein.',
}
