TEXTS = {
    'team_recruit_heading': 'Mitglieder hinzufügen',
    'team_recruit_clan': 'Aus meinem Clan',
    'team_recruit_clan_hint': 'Bestätigte Mitglieder deines Clans werden ohne Rückfrage aufgenommen. Ein späterer Clanaustritt ändert die Teammitgliedschaft nicht.',
    'team_recruit_clan_empty': 'Keine verfügbaren Clanmitglieder gefunden.',
    'team_recruit_no_clan': 'Du gehörst derzeit keinem bestätigten Clan an.',
    'team_recruit_add_selected': 'Ausgewählte Mitglieder hinzufügen',
    'team_recruit_search': 'Spieler suchen',
    'team_recruit_search_hint': 'Suche nach Nickname (mindestens zwei Zeichen). Mitglieder deines Clans werden direkt hinzugefügt; andere Spieler müssen die persönliche Einladung bestätigen.',
    'team_recruit_search_label': 'Nickname',
    'team_recruit_search_button': 'Suchen',
    'team_recruit_search_empty': 'Keine verfügbaren Spieler gefunden.',
    'team_recruit_search_limit': 'Es werden höchstens 20 Treffer angezeigt. Verfeinere bei Bedarf deine Suche.',
    'team_recruit_add': 'Hinzufügen',
    'team_recruit_invite': 'Einladen',
    'team_recruit_same_clan': 'Dein Clan',
    'team_recruit_added': '{count} Clanmitglied(er) wurden dem Team hinzugefügt.',
    'team_recruit_invited': 'Einladung an {username} gesendet.',
    'team_recruit_forbidden': 'Nur der aktuelle Teamkapitän kann Mitglieder hinzufügen oder Einladungen verwalten.',
    'team_recruit_unavailable': 'Das Team ist archiviert, gehört zu einer anderen Veranstaltung oder die Veranstaltung ist beendet. Mitglieder können derzeit nicht hinzugefügt werden.',
    'team_recruit_locked': 'Während eines laufenden oder bereits generierten Turniers kann der Kader nicht erweitert werden.',
    'team_recruit_solo': 'Einzelspieler-Teams können keine weiteren Mitglieder aufnehmen.',
    'team_recruit_full': 'Für diese Auswahl hat das Team nicht genügend freie Kaderplätze.',
    'team_recruit_player_unavailable': 'Der ausgewählte Spieler ist nicht verfügbar.',
    'team_recruit_already_member': '{username} ist bereits Mitglied dieses Teams.',
    'team_recruit_other_team': '{username} gehört für dieses Spiel bereits einem anderen aktiven Team an.',
    'team_recruit_select': 'Bitte wähle mindestens ein Clanmitglied aus.',
    'team_recruit_clan_changed': 'Mindestens ein ausgewählter Spieler gehört nicht mehr zu deinem bestätigten Clan. Bitte lade die Seite neu.',
    'team_recruit_pending_application': '{username} hat sich bereits beworben. Bitte bearbeite die vorhandene Bewerbung.',
    'team_recruit_pending_invitation': 'Für {username} ist bereits eine Einladung offen.',
    'team_invitation_received': 'Meine Einladungen',
    'team_invitation_sent': 'Gesendete Einladungen',
    'team_invitation_from': 'Eingeladen von {username}',
    'team_invitation_no_reservation': 'Offene Einladungen reservieren keinen Kaderplatz. Beim Annehmen werden freie Plätze und deine Teammitgliedschaften erneut geprüft.',
    'team_invitation_accept': 'Annehmen',
    'team_invitation_decline': 'Ablehnen',
    'team_invitation_withdraw': 'Zurückziehen',
    'team_invitation_accepted': 'Du bist dem Team {team_name} beigetreten.',
    'team_invitation_declined': 'Einladung abgelehnt.',
    'team_invitation_withdrawn': 'Einladung zurückgezogen.',
    'team_invitation_not_open': 'Diese Einladung ist nicht mehr offen oder nicht mehr gültig.',
    'team_invitation_recipient_only': 'Nur der eingeladene Spieler darf diese Einladung beantworten.',
    'team_invitation_existing_hint': 'Du hast bereits eine persönliche Einladung für dieses Team. Bitte nimm sie an oder lehne sie ab.',
    'team_application_decline': 'Bewerbung ablehnen',
    'team_application_declined': 'Bewerbung abgelehnt.',
    'team_application_not_pending': 'Diese Bewerbung ist nicht mehr offen.',
    'team_direct_addition_notice': '{username} hat dich dem Team {team_name} hinzugefügt. Eine Bestätigung ist nicht erforderlich.',
    'team_attention_title': '{count} offene Bewerbung(en) oder Einladung(en)',
}
