TEXTS = {
    'ban_registration_failed': 'Die Registrierung konnte nicht abgeschlossen werden. Bitte wende dich an die Organisatoren.',
    'ban_access_failed': 'Diese Aktion ist derzeit nicht möglich. Bitte wende dich an die Organisatoren.',
    'ban_checkin_failed': 'Check-in nicht möglich. Bitte die Veranstaltungsleitung kontaktieren.',
    'ban_manage': 'Benutzer sperren / Sperre aufheben',
    'ban_confirm': 'Globale Sperre bestätigen',
    'ban_revoke': 'Sperre manuell aufheben',
    'ban_reason': 'Interne Begründung',
    'ban_hint': 'Die globale Sperre gilt bis zur manuellen Aufhebung. Login, neue Anmeldungen und Check-in werden blockiert; vorhandene Tickets werden entwertet. Buchungen, Zahlungen und Turnierergebnisse bleiben erhalten.',
    'ban_identity_hint': 'Bestätigte E-Mail-Adressen bleiben auch nach einer Accountlöschung gesperrt. Andere Adressen und eine manuelle Kontrolle beim Einlass müssen separat berücksichtigt werden.',
    'ban_success': 'Die globale Sperre wurde gespeichert.',
    'ban_revoke_success': 'Die Sperre wurde aufgehoben. Alte Sitzungen und QR-Tickets bleiben ungültig.',
    'ban_reason_required': 'Bitte eine Begründung mit maximal 1000 Zeichen angeben.',
    'ban_permission': 'Keine Berechtigung zur Verwaltung von Orga-Sperren.',
    'ban_self': 'Das eigene Benutzerkonto kann nicht gesperrt werden.',
    'ban_privileged': 'Mitarbeiter und administrative Konten können nur durch einen Superuser gesperrt werden.',
    'ban_deleted': 'Der Account wurde gelöscht. Bekannte E-Mail-Adressen können über die Orga-Sperrliste gesperrt werden.',
    'ban_stale': 'Der Benutzer oder die Sperre wurde inzwischen geändert. Bitte die Seite neu laden.',
    'ban_already_active': 'Es besteht bereits eine aktive Sperre.',
    'ban_key_missing': 'USER_BAN_HMAC_KEY muss mit mindestens 32 zufälligen Zeichen konfiguriert werden.',
    'ban_key_changed': 'Der Sperrlisten-Schlüssel passt nicht zu bestehenden aktiven Einträgen. Bitte die bisherige Konfiguration wiederherstellen.',
    'ban_email_unverified': 'Die Account-Sperre ist aktiv. Die unbestätigte E-Mail-Adresse wurde nicht automatisch in die Registrierungssperrliste übernommen.',
}
