# Generated by Django 6.0.7 on 2026-07-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Veranstaltungsinformationen', max_length=200, verbose_name='Seitentitel')),
                ('subtitle', models.CharField(blank=True, default='Alle Fakten zur LAN im Überblick', max_length=300, verbose_name='Untertitel')),
                ('content', models.TextField(help_text='Hier kannst du den Haupttext der Informationsseite verfassen und formatieren.', verbose_name='Inhalt (Text / HTML / Markdown)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zuletzt geändert')),
            ],
            options={
                'verbose_name': 'Veranstaltungsinformation',
                'verbose_name_plural': 'Veranstaltungsinformationen',
            },
        ),
    ]
