# Generated by Django 6.0.7 on 2026-07-24 12:55

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinfo',
            name='content',
            field=tinymce.models.HTMLField(help_text='Hier kannst du den Haupttext verfassen und bequem formatieren.', verbose_name='Inhalt'),
        ),
    ]
