# Generated by Django 6.0.7 on 2026-09-07 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0016_systemerrorlog'),
        ('info', '0002_alter_eventinfo_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventinfo',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Inhaltsseite / Infoseite', 'verbose_name_plural': 'Inhaltsseiten / Infoseiten'},
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Erstellt am'),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inaktive Seiten sind für normale Besucher nicht sichtbar.', verbose_name='Veröffentlicht?'),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='login_required',
            field=models.BooleanField(default=False, help_text='Schützt sensible Informationen (z. B. WLAN-Zugang, Vor-Ort-Hinweise).', verbose_name='Nur für angemeldete Benutzer?'),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='nav_icon',
            field=models.CharField(choices=[('dashboard', 'Dashboard / Übersicht (Home)'), ('tournaments', 'Turniere (Pokal / Trophy)'), ('teams', 'Teams (Spielergruppe)'), ('seating', 'Sitzplan (Raster / Grid)'), ('info', 'Informationen (Info-Kreis)'), ('news', 'Neuigkeiten (Zeitung / Feed)'), ('clans', 'Clans (Schild / Wappen)'), ('rules', 'Regeln & FAQ (Buch / Dokument)'), ('support', 'Support & Hilfe (Rettungsring)'), ('shop', 'Shop & Catering (Einkaufswagen)'), ('settings', 'Einstellungen (Regler)'), ('sponsors', 'Sponsoren (Stern / Partner)'), ('custom', 'Benutzerdefiniertes SVG (Nur Superuser)')], default='info', help_text='Icon für den Menüpunkt, falls im Hauptmenü angezeigt.', max_length=50, verbose_name='Menü-Icon'),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='nav_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='info_page', to='configuration.navigationitem', verbose_name='Verknüpfter Menüpunkt'),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Bestimmt die Position in der Tab-Leiste und im Menü.', verbose_name='Reihenfolge'),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='show_in_nav',
            field=models.BooleanField(default=False, help_text='Erstellt automatisch einen Menüpunkt in der linken Seitenleiste.', verbose_name='In Hauptnavigation anzeigen?'),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='slug',
            field=models.SlugField(default='allgemein', help_text="Wird für die URL verwendet (z. B. 'allgemein', 'catering', 'regeln').", max_length=100, unique=True, verbose_name='URL-Kürzel (Slug)'),
        ),
    ]
