# Generated by Django 6.0.7 on 2026-10-06 19:12

import django.core.validators
import django.db.models.deletion
import info.embedding
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_eventinfo_options_eventinfo_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbedProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('origin', models.URLField(help_text='Nur Schema, Host und optional Port, z. B. https://galerie.example.com.', max_length=255, unique=True, validators=[info.embedding.validate_embed_origin], verbose_name='Erlaubte HTTPS-Origin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Einbettung freigegeben?')),
            ],
            options={
                'verbose_name': 'Einbettungsanbieter',
                'verbose_name_plural': 'Einbettungsanbieter',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='embed_height',
            field=models.PositiveIntegerField(default=800, help_text='Zwischen 320 und 2000 Pixeln.', validators=[django.core.validators.MinValueValidator(320), django.core.validators.MaxValueValidator(2000)], verbose_name='Rahmenhöhe (Pixel)'),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='embed_profile',
            field=models.CharField(choices=[('STATIC', 'Statische Seite (ohne JavaScript)'), ('GALLERY', 'Interaktive Galerie (JavaScript, Speicher, Downloads, Vollbild)')], default='GALLERY', max_length=10, verbose_name='Einbettungsprofil'),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='embed_url',
            field=models.URLField(blank=True, default='', help_text='HTTPS-Adresse auf der freigegebenen Origin. Keine Zugangsdaten eintragen.', max_length=2048, verbose_name='Einbettungsadresse'),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='embed_wide',
            field=models.BooleanField(default=True, verbose_name='Breite Ansicht verwenden?'),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='page_type',
            field=models.CharField(choices=[('TEXT', 'Textseite'), ('EMBED', 'Externe Einbettung')], default='TEXT', max_length=10, verbose_name='Seitentyp'),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='content',
            field=tinymce.models.HTMLField(blank=True, help_text='Hier kannst du den Haupttext verfassen und bequem formatieren.', verbose_name='Inhalt'),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='embed_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='info.embedprovider', verbose_name='Einbettungsanbieter'),
        ),
    ]
