# Generated by Django 6.0.7 on 2026-07-31 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Clanname')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL-Slug')),
                ('website', models.URLField(blank=True, verbose_name='Website URL')),
                ('logo', models.FileField(blank=True, null=True, upload_to='clan_logos/', verbose_name='Clan-Logo')),
                ('password', models.CharField(help_text='Passwort für sofortigen Direktbeitritt', max_length=100, verbose_name='Clan-Passwort')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zuletzt geändert')),
            ],
            options={
                'verbose_name': 'Clan',
                'verbose_name_plural': 'Clans',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClanMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Clan-Admin'), ('MEMBER', 'Clan-Mitglied')], default='MEMBER', max_length=10, verbose_name='Rolle')),
                ('status', models.CharField(choices=[('ACCEPTED', 'Mitglied'), ('PENDING', 'Anfrage ausstehend')], default='ACCEPTED', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Beigetreten / Angefragt am')),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='clans.clan', verbose_name='Clan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Clan-Mitgliedschaft',
                'verbose_name_plural': 'Clan-Mitgliedschaften',
                'ordering': ['role', 'created_at'],
                'unique_together': {('user', 'clan')},
            },
        ),
    ]
