# Generated by Django 6.0.7 on 2026-08-14 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clan_logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Clan-Logo'),
        ),
        migrations.AlterField(
            model_name='clan',
            name='password',
            field=models.CharField(help_text='Passwort für sofortigen Direktbeitritt (wird sicher gehasht gespeichert)', max_length=128, verbose_name='Clan-Passwort (Gehasht)'),
        ),
    ]
