# Generated by Django 6.0.7 on 2026-09-09 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0003_hash_plaintext_clan_passwords'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='clanmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACCEPTED')), fields=('user',), name='unique_active_clan_membership_per_user', violation_error_message='Ein Benutzer kann zu jedem Zeitpunkt nur in genau einem aktiven Clan Mitglied sein.'),
        ),
    ]
