# Generated by Django 6.0.7 on 2026-09-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0004_clanmembership_unique_active_clan_membership_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='Clan-Tag'),
        ),
        migrations.AlterField(
            model_name='clan',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Clanname'),
        ),
    ]
