# Generated by Django 6.0.7 on 2026-10-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0005_clan_tag_alter_clan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='seat_limit_override',
            field=models.PositiveIntegerField(blank=True, help_text='Leer: globaler Standard. 0: gesperrt und offene Vormerkungen freigeben. Nur durch die Orga änderbar.', null=True, verbose_name='Sitzplatzkontingent (optional)'),
        ),
    ]
