# Generated by Django 6.0.7 on 2026-10-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0006_clan_seat_limit_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='seat_limit_override',
            field=models.PositiveIntegerField(blank=True, help_text='Leer: globaler Standard. 0: neue Vormerkungen sperren und offene Plätze ohne Sammelauftrag freigeben. Sammelaufträge bleiben erhalten. Nur durch die Orga änderbar.', null=True, verbose_name='Sitzplatzkontingent (optional)'),
        ),
    ]
