# Generated by Django 6.0.7 on 2026-07-23 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_event_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Hallenbezeichnung')),
                ('columns', models.PositiveIntegerField(default=20, verbose_name='Spaltenanzahl (X)')),
                ('rows', models.PositiveIntegerField(default=15, verbose_name='Zeilenanzahl (Y)')),
                ('location_info', models.TextField(blank=True, help_text='Informationen zu Parkplätzen, Strom, Catering etc.', verbose_name='Hallen- & Anfahrts-Infos')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating_plans', to='events.event', verbose_name='Veranstaltung')),
            ],
            options={
                'verbose_name': 'Sitzplan / Halle',
                'verbose_name_plural': 'Sitzpläne / Hallen',
            },
        ),
        migrations.CreateModel(
            name='SeatingCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField(verbose_name='Spalte X')),
                ('y', models.PositiveIntegerField(verbose_name='Zeile Y')),
                ('cell_type', models.CharField(choices=[('EMPTY', 'Freie Fläche / Gang'), ('SEAT', 'Sitzplatz'), ('WALL', 'Wand / Hindernis'), ('DOOR', 'Tür / Notausgang'), ('LABEL', 'Beschriftung / Text')], default='EMPTY', max_length=10, verbose_name='Kachel-Typ')),
                ('seat_label', models.CharField(blank=True, max_length=20, verbose_name='Sitzplatz-Bezeichnung')),
                ('text_label', models.CharField(blank=True, max_length=50, verbose_name='Beschriftungstext')),
                ('reservation_status', models.CharField(choices=[('FREE', 'Frei'), ('PRE', 'Vorgemerkt (Nicht bezahlt)'), ('RESERVED', 'Fest reserviert (Bezahlt)'), ('BLOCKED', 'Vom Admin gesperrt')], default='FREE', max_length=10, verbose_name='Reservierungs-Status')),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats', to='events.eventregistration', verbose_name='Zugewiesener Teilnehmer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='seating.seatingplan', verbose_name='Sitzplan')),
            ],
            options={
                'verbose_name': 'Raster-Kachel',
                'verbose_name_plural': 'Raster-Kacheln',
                'unique_together': {('plan', 'x', 'y')},
            },
        ),
    ]
