# Generated by Django 6.0.7 on 2026-07-23 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_is_active'),
        ('seating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatingplan',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seating_plans', to='events.event', verbose_name='Veranstaltung'),
        ),
    ]
