# Generated by Django 6.0.7 on 2026-08-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_event_end_date_after_start_date'),
        ('seating', '0003_alter_seatingplan_event'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='seatingcell',
            constraint=models.CheckConstraint(condition=models.Q(('x__gte', 1), ('y__gte', 1)), name='seating_cell_coords_positive', violation_error_message='Sitzplatz-Koordinaten müssen positiv (>= 1) sein.'),
        ),
    ]
