# Generated by Django 6.0.7 on 2026-09-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_allow_unpaid_seat_overwrite'),
        ('seating', '0006_seatingcell_indexes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seatingcell',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='seatingcell',
            constraint=models.UniqueConstraint(fields=('plan', 'x', 'y'), name='unique_cell_coordinate_per_plan'),
        ),
        migrations.AddConstraint(
            model_name='seatingcell',
            constraint=models.UniqueConstraint(condition=models.Q(('registration__isnull', False)), fields=('registration',), name='unique_seat_per_registration', violation_error_message='Ein Teilnehmer kann maximal einen Sitzplatz gleichzeitig reservieren.'),
        ),
    ]
