# Generated by Django 6.0.7 on 2026-09-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0007_seatingcell_unique_seat_per_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatingplan',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Inkrementeller Versionszähler für Optimistic Concurrency Control im Editor.', verbose_name='Layout-Version'),
        ),
    ]
