# Generated by Django 6.0.7 on 2026-10-04 10:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0006_clan_seat_limit_override'),
        ('events', '0014_eventregistration_booking_price'),
        ('seating', '0008_seatingplan_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanSeatAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.CharField(max_length=5)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('reminder_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_allocations', to='clans.clan')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_seat_allocations', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='ClanSeatHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_label', models.CharField(max_length=40)),
                ('state', models.CharField(choices=[('OPEN', 'Offen'), ('CLAIMED', 'Übernommen'), ('RELEASED', 'Freigegeben')], default='OPEN', max_length=8)),
                ('protection_active', models.BooleanField(default=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='seating.clanseatallocation')),
                ('cell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clan_holds', to='seating.seatingcell')),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='clanseatallocation',
            constraint=models.UniqueConstraint(fields=('clan', 'event'), name='unique_clan_event_allocation'),
        ),
        migrations.AddConstraint(
            model_name='clanseathold',
            constraint=models.UniqueConstraint(condition=models.Q(('protection_active', True)), fields=('cell',), name='unique_protected_clan_seat'),
        ),
    ]
