# Generated by Django 6.0.7 on 2026-10-07 20:01

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import seating.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_eventregistration_booking_price'),
        ('seating', '0009_clanseatallocation_clanseathold_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clanseathold',
            name='funded_registration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clan_funding', to='events.eventregistration'),
        ),
        migrations.AddField(
            model_name='clanseathold',
            name='registration_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ClanSeatPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_name', models.CharField(max_length=50)),
                ('seat_count', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(default=seating.models.clan_payment_reference, editable=False, max_length=24, unique=True)),
                ('beneficiary_name', models.CharField(max_length=70)),
                ('iban', models.CharField(max_length=34)),
                ('bic', models.CharField(blank=True, max_length=11)),
                ('status', models.CharField(choices=[('PENDING', 'Zahlung ausstehend'), ('PAID', 'Bezahlt'), ('CANCELLED', 'Storniert')], db_index=True, default='PENDING', max_length=9)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_due_at', models.DateTimeField()),
                ('release_at', models.DateTimeField(db_index=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('reminder_at', models.DateTimeField(blank=True, null=True)),
                ('allocation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='seating.clanseatallocation')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.tickettype')),
            ],
            options={
                'verbose_name': 'Clan-Sammelzahlung',
                'verbose_name_plural': 'Clan-Sammelzahlungen',
                'permissions': [('manage_clan_payments', 'Clan-Zahlungen bestätigen und Zuweisungen korrigieren')],
            },
        ),
        migrations.AddField(
            model_name='clanseathold',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='holds', to='seating.clanseatpayment'),
        ),
        migrations.CreateModel(
            name='ClanSeatPaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('details', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='seating.clanseatpayment')),
            ],
            options={
                'verbose_name': 'Clan-Zahlungsprotokoll',
                'verbose_name_plural': 'Clan-Zahlungsprotokolle',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='clanseatpayment',
            constraint=models.CheckConstraint(condition=models.Q(('seat_count__gte', 1), ('unit_price__gt', 0)), name='clan_payment_positive'),
        ),
        migrations.AddConstraint(
            model_name='clanseatpayment',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount', django.db.models.expressions.CombinedExpression(models.F('unit_price'), '*', models.F('seat_count')))), name='clan_payment_amount_matches'),
        ),
        migrations.AddConstraint(
            model_name='clanseatpayment',
            constraint=models.CheckConstraint(condition=models.Q(('payment_due_at__gt', models.F('created_at')), ('release_at__gte', models.F('payment_due_at'))), name='clan_payment_dates_ordered'),
        ),
    ]
