TEXTS = {
    'clan_admins_title': 'Clan-Admins',
    'clan_admins_description': 'Alle Clan-Admins haben dieselben Rechte. Die Anzahl ist unbegrenzt.',
    'clan_demote_btn': 'Als Mitglied setzen',
    'clan_promote_question': 'Zum Clan-Admin machen? Diese Person erhält alle Adminrechte für den Clan.',
    'clan_demote_question': 'Adminrolle entziehen? Die Person bleibt Mitglied des Clans.',
    'clan_last_admin_hint': 'Letzter aktiver Clan-Admin: Die Adminrolle kann nicht entzogen werden.',
    'clan_role_confirm_btn': 'Änderung bestätigen',
    'clan_role_cancel_btn': 'Abbrechen',
    'msg_clan_role_promoted': '{username} wurde zum Clan-Admin befördert.',
    'msg_clan_role_demoted': '{username} ist jetzt Clan-Mitglied ohne Adminrechte.',
    'msg_clan_role_unchanged': 'Diese Rolle ist bereits gesetzt. Bitte lade das Clanprofil neu.',
    'msg_clan_role_confirmation': 'Bitte bestätige die Rollenänderung im Clanprofil.',
    'msg_clan_last_admin': 'Mindestens ein aktiver Clan-Admin muss erhalten bleiben. Befördere zuerst ein anderes Mitglied.',
    'msg_clan_active_member_required': 'Adminrechte können nur aktive, bestätigte Clan-Mitglieder erhalten.',
    'msg_clan_confirmed_member_required': 'Diese Aktion ist nur für bestätigte Clan-Mitglieder möglich.',
    'msg_clan_pending_required': 'Diese Beitrittsanfrage ist nicht mehr offen. Bitte lade das Clanprofil neu.',
    'msg_clan_invalid_action': 'Unbekannte Clan-Aktion.',
    'msg_clan_membership_changed': 'Die Mitgliedschaft wurde inzwischen geändert. Bitte lade das Clanprofil neu.',
    'msg_clan_no_permission': 'Keine Berechtigung.',
    'msg_clan_not_member': 'Du bist kein aktives Mitglied dieses Clans.',
    'msg_clan_self_kick': 'Du kannst dich nicht selbst entfernen. Nutze „Clan verlassen“.',
}
